<?php
echo '<!DOCTYPE html>';
echo '<html dir="ltr">';
echo '';
echo '<head>';
echo '<title>';
echo 'SubRocks - testrocks  </title>';
echo '<meta property="og:title" content="SubRocks - testrocks" />';
echo '<meta property="og:url" content="https://subrock.rocks/" />';
echo '<meta property="og:description" content="SubRocks is a site dedicated to bring back the 2012 layout of YouTube." />';
echo '<meta property="og:image" content="/yt/imgbin/full-size-logo.png" />';
echo '<script>';
echo 'var yt = yt || {}; yt.timing = yt.timing || {}; yt.timing.tick = function (label, opt_time) { var timer = yt.timing['timer'] || {}; if (opt_time) { timer[label] = opt_time; } else { timer[label] = new Date().getTime(); } yt.timing['timer'] = timer; }; yt.timing.info = function (label, value) { var info_args = yt.timing['info_args'] || {}; info_args[label] = value; yt.timing['info_args'] = info_args; }; yt.timing.info('e', "904821,919006,922401,920704,912806,913419,913546,913556,919349,919351,925109,919003,920201,912706"); if (document.webkitVisibilityState == 'prerender') { document.addEventListener('webkitvisibilitychange', function () { yt.timing.tick('start'); }, false); } yt.timing.tick('start'); yt.timing.info('li', '0'); try { yt.timing['srt'] = window.gtbExternal && window.gtbExternal.pageT() || window.external && window.external.pageT; } catch (e) { } if (window.chrome && window.chrome.csi) { yt.timing['srt'] = Math.floor(window.chrome.csi().pageT); } if (window.msPerformance && window.msPerformance.timing) { yt.timing['srt'] = window.msPerformance.timing.responseStart - window.msPerformance.timing.navigationStart; }';
echo '</script>';
echo '<link id="www-core-css" rel="stylesheet" href="/yt/cssbin/www-core-vfluMRDnk.css">';
echo '<link rel="stylesheet" href="/yt/cssbin/www-guide-vflx0V5Tq.css">';
echo '<link rel="stylesheet" href="/yt/cssbin/www-videos-nav-vflYGt27y.css">';
echo '<link rel="stylesheet" href="/yt/cssbin/www-extra.css">';
echo '<link rel="stylesheet" href="/yt/cssbin/www-inbox.css">';
echo '<script src="//s.ytimg.com/yt/jsbin/www-browse-vflu1nggJ.js" data-loaded="true"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"';
echo 'integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="';
echo 'crossorigin="anonymous" referrerpolicy="no-referrer"></script>';
echo '<script>';
echo 'if (window.yt.timing) { yt.timing.tick("ct"); }';
echo '</script>';
echo '<style>';
echo '.master-myaccount-top {';
echo 'border-bottom: 1px solid #CACACA;';
echo '}';
echo '';
echo '.www-home-left a {';
echo 'padding-bottom: 3px;';
echo 'padding-top: 4px;';
echo 'font-weight: 700;';
echo 'text-align: left;';
echo 'color: black;';
echo 'padding-left: 2px;';
echo 'width: 193px;';
echo 'display: inline-block;';
echo '}';
echo '';
echo '.www-home-left {';
echo 'width: 200px;';
echo 'border-right: 1px solid #aaa;';
echo '}';
echo '';
echo '.www-home-right {';
echo 'width: 754px;';
echo 'padding: 5px;';
echo '}';
echo '';
echo '.www-home-left a:hover {';
echo 'background-color: rgb(239, 239, 239);';
echo 'background: -moz-linear-gradient(0deg, rgb(192, 192, 192, 1)0%, rgb(239, 239, 239, 1)115%);';
echo 'background: -webkit-linear-gradient(0deg, rgb(192, 192, 192, 1)0%, rgb(239, 239, 239, 1)115%);';
echo 'background: linear-gradient(0deg, rgb(192, 192, 192)0%, rgb(239, 239, 239)115%);';
echo 'filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="c0c0c0", endColorstr="#efefef", GradientType=1);';
echo '}';
echo '';
echo 'a[href="/inbox/send"] {';
echo 'margin: 0px !important;';
echo 'padding: 0px !important;';
echo 'position: relative;';
echo 'top: 0px !important;';
echo '}';
echo '';
echo '#search-button {';
echo 'margin: 0px;';
echo 'margin-bottom: 7px;';
echo 'margin-top: 4px;';
echo '}';
echo '';
echo 'table {';
echo 'font-family: arial, sans-serif;';
echo 'border-collapse: collapse;';
echo 'width: 100%;';
echo '}';
echo '';
echo 'td,';
echo 'th {';
echo 'text-align: left;';
echo 'padding: 3px;';
echo '}';
echo '';
echo 'th {';
echo 'border: 1px solid #dddddd;';
echo 'background: rgb(215, 215, 215);';
echo 'background: -moz-linear-gradient(0deg, rgba(215, 215, 215, 1) 0%, rgba(255, 255, 255, 1) 100%);';
echo 'background: -webkit-linear-gradient(0deg, rgba(215, 215, 215, 1) 0%, rgba(255, 255, 255, 1) 100%);';
echo 'background: linear-gradient(0deg, rgba(215, 215, 215, 1) 0%, rgba(255, 255, 255, 1) 100%);';
echo 'filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#d7d7d7", endColorstr="#ffffff", GradientType=1);';
echo 'height: 14px;';
echo 'font-weight: lighter;';
echo '}';
echo '';
echo 'tr:nth-child(even) {';
echo 'background-color: #f9f9f9;';
echo '}';
echo '';
echo '.video-manager-info {';
echo 'width: 462px;';
echo '}';
echo '';
echo '.video-filter-options a {';
echo 'margin-left: 5px;';
echo 'margin-right: 5px;';
echo '}';
echo '';
echo '.selected {';
echo 'font-weight: bold;';
echo 'color: black;';
echo '}';
echo '</style>';
echo '</head>';
echo '';
echo '<body id="" class="date-20120930 en_US ltr   ytg-old-clearfix guide-feed-v2 " dir="ltr">';
echo '<form name="logoutForm" method="POST" action="/logout">';
echo '<input type="hidden" name="action_logout" value="1">';
echo '</form>';
echo '<!-- begin page -->';
echo '<div id="page" class="browse-base">';
echo '<!-- begin pagetop -->';
echo '<div id="masthead-container">';
echo '<script>';
echo '// Check if user is using Internet Explorer';
echo 'function detectIE() {';
echo 'var ua = window.navigator.userAgent;';
echo 'var msie = ua.indexOf('MSIE ');';
echo 'if (msie > 0) {';
echo '// IE 10 or older';
echo 'return true;';
echo '}';
echo 'var trident = ua.indexOf('Trident/');';
echo 'if (trident > 0) {';
echo '// IE 11';
echo 'return true;';
echo '}';
echo 'var edge = ua.indexOf('Edge/');';
echo 'if (edge > 0) {';
echo '// Edge (IE 12+)';
echo 'return true;';
echo '}';
echo 'return false;';
echo '}';
echo '';
echo '// Insert div if user is using Internet Explorer';
echo 'window.onload = function() {';
echo 'if (detectIE()) {';
echo 'var alertsDiv = document.querySelector('.alerts-2012');';
echo 'var ieDiv = document.createElement('div');';
echo 'ieDiv.id = 'ie-div';';
echo 'ieDiv.className = 'yt-alert yt-alert-default yt-alert-error hid';';
echo 'ieDiv.innerHTML = '<div class="yt-alert-icon"><img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="icon master-sprite" alt="Alert icon"></div><div class="yt-alert-buttons"></div><div class="yt-alert-content" role="alert"><span class="yt-alert-vertical-trick"></span><div class="yt-alert-message">You are using Microsoft Internet Explorer web browser. SubRocks is ending support for Internet Explorer soon, <a href="/supported_browsers">update your browser now</a>.</div></div>';';
echo 'alertsDiv.appendChild(ieDiv);';
echo 'ieDiv.style.display = 'block';';
echo '}';
echo '}';
echo '</script>';
echo '<!-- Google tag (gtag.js) -->';
echo '<script async src="https://www.googletagmanager.com/gtag/js?id=G-KZRLW5PBQD"></script>';
echo '<script>';
echo 'window.dataLayer = window.dataLayer || [];';
echo 'function gtag(){dataLayer.push(arguments);}';
echo 'gtag('js', new Date());';
echo '';
echo 'gtag('config', 'G-KZRLW5PBQD');';
echo '</script>';
echo '<!-- begin masthead -->';
echo '<div id="masthead" class="" dir="ltr">';
echo '<a id="logo-container" href="/" title="SubRocks home">';
echo '<img id="logo" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" width="100" height="40" alt="SubRocks home">';
echo '</a>';
echo '<div id="masthead-user-bar-container">';
echo '<div id="masthead-user-bar">';
echo '<div id="masthead-user">';
echo '<a class="start" href="/sign_up">Create Account</a><span class="masthead-link-separator">|</span><a class="end" href="/sign_in">Sign In</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="masthead-search-bar-container">';
echo '<div id="masthead-search-bar">';
echo '<div id="masthead-nav"><a href="/videos?feature=mh">Browse</a><span class="masthead-link-separator">|</span><a id="masthead-upload-link" class="" data-upsell="upload" href="/upload_video">Upload</a></div>';
echo '<form id="masthead-search" class="search-form consolidated-form" action="/results" onsubmit="if (_gel('masthead-search-term').value == '') return false;">';
echo '<button class="search-btn-compontent search-button yt-uix-button yt-uix-button-default" onclick="if (_gel('masthead-search-term').value == '') return false; _gel('masthead-search').submit(); return false;;return true;" type="submit" id="search-btn" dir="ltr" tabindex="2" role="button"><span class="yt-uix-button-content">Search </span></button>';
echo '<div id="masthead-search-terms" class="masthead-search-terms-border" dir="ltr"><label><input id="masthead-search-term" autocomplete="off" class="search-term" name="search_query" value="" type="text" tabindex="1" onkeyup="goog.i18n.bidi.setDirAttribute(event,this)" title="Search"></label></div>';
echo '</form>';
echo '</div>';
echo '</div></div>';
echo '<div class="alerts-2012">';
echo '';
echo '</div>';
echo '<!--';
echo '<div id="ticker" class="ytg-base "><div id="ticker-inner"><div class="ytg-wide"><button onclick="yt.net.cookies.set('HideTicker', 1, 604800);" class="yt-uix-close" data-close-parent-id="ticker"><img alt="Close" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif"></button><img class="ticker-icon" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><div class="ticker-content">';
echo '<b>New minor update: <pre style="display:inline-block;">1fe1fa4</pre></b> <pre style="display:inline-block;font-size:10px;margin-left:35px;">This is a part of the Communications update. The inbox has been updated with a cleaner look.</pre>';
echo '</div></div></div></div><br>';
echo '-->';
echo '<div id="alerts">';
echo '';
echo '</div>';
echo '<!-- end masthead -->';
echo '</div>';
echo '<!-- end pagetop -->';
echo '<!-- begin pagemiddle -->';
echo '<div id="content-container">';
echo '<div id="baseDiv" class="date-20120930 video-info   browse-base browse-videos">';
echo '<div id="alerts"></div>';
echo '<div id="masthead-subnav" class="yt-nav yt-nav-dark ">';
echo '<ul>';
echo '<a href="/t/about_subrocks">';
echo '<li class="">';
echo '<span class="yt-nav-item">';
echo 'SubRocks';
echo '</span>';
echo '</li>';
echo '</a>';
echo '<a href="/t/dev">';
echo '<li class=" selected">';
echo '<span class="yt-nav-item">';
echo 'Developers';
echo '</span>';
echo '</li>';
echo '</a>';
echo '</ul>';
echo '</div>';
echo '<div class="browse-container ytg-wide ytg-box no-stage browse-bg-gradient">';
echo '<div class="ytg-fl browse-content">';
echo '';
echo '<div id="browse-side-column" class="ytg-2col ytg-last">';
echo '<ol class="navigation-menu">';
echo '<li class="menu-item">';
echo '<a class="1" href="/t/dev">';
echo 'Developers                </a>';
echo '</li>';
echo '<li class="menu-item">';
echo '<a class="selected" href="/t/testrocks">';
echo 'testrocks                </a>';
echo '</li>';
echo '</ol>';
echo '</div>';
echo '<div id="browse-main-column" style="float: right;margin: 0px 0 0 14px;" class="ytg-4col">';
echo '<div class="browse-collection  has-box-ad">';
echo '<h1>TestRocks</h1>';
echo '<hr><br>';
echo '<div id="article-container" class="ytg-box">';
echo '<p>';
echo 'Welcome to TestRocks, our ideas incubator. This is where SubRocks engineers and';
echo 'developers test out recipes and concoctions that aren't quite fully baked and';
echo 'invite you to tell us how they're coming along.';
echo '</p>';
echo '<p>';
echo 'Your comments will help us improve and perfect the mixtures we're working on. So';
echo 'jump in, play around, and send your feedback directly to the brains behind the';
echo 'scenes.';
echo '</p>';
echo '';
echo '<div>';
echo '<a class="icon" href="/2009/">';
echo '<img src="/yt/imgbin/testrocks-2009-vfl26Dox4.gif"';
echo 'width="103" height="74" border="0" alt="SubRocks 2009">';
echo '</a>';
echo '<h3>SubRocks 2009</h3>';
echo '<p>Want to use our 2009 UI? It's in very early stages of development.</p>';
echo '<p>';
echo '<strong><a';
echo 'href="/2009/">Try out 2009</a></strong> &nbsp;|&nbsp; <a';
echo 'href="/redirect/discord">Feedback?</a>';
echo '</p>';
echo '</div>';
echo '';
echo '<div>';
echo '<a class="icon" href="/2013/">';
echo '<img src="/yt/imgbin/testrocks-html5-vfl26Dox4.gif"';
echo 'width="103" height="74" border="0" alt="SubRocks 2013">';
echo '</a>';
echo '<h3>SubRocks 2013</h3>';
echo '<p>';
echo 'Want to use our 2013 UI? It's in very early stages of development.<br>';
echo '<strong>';
echo '<a href="/2013/">Try';
echo 'out 2013</a> &nbsp;|&nbsp; <a';
echo 'href="/redirect/discord">Feedback?</a>';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="clear"></div>';
echo '</div>';
echo '</div>';
echo '<!-- end pagemiddle -->';
echo '<!-- begin pagebottom -->';
echo '<div id="footer-container">';
echo '<!-- begin footer -->';
echo '<div id="footer">';
echo '<div class="yt-horizontal-rule "><span class="first"></span><span class="second"></span><span class="third"></span></div>';
echo '<div id="footer-logo">';
echo '<a href="/" title="SubRock home">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="SubRock home">';
echo '</a>';
echo '<span id="footer-divider"></span>';
echo '</div>';
echo '<div id="footer-main">';
echo '<ul id="footer-links-primary">';
echo '<li><a href="/t/about_subrocks">About</a></li>';
echo '<li><a href="/t/copyright_center">Copyright</a></li>';
echo '<li><a href="/t/community_guidelines">Guidelines</a></li>';
echo '<li><a href="/t/partners">Partners</a></li>';
echo '</ul>';
echo '<ul id="footer-links-secondary">';
echo '<li><a href="/t/terms">Terms</a></li>';
echo '<li><a id="discord" href="/redirect/discord">Discord</a></li>';
echo '<li><a href="/t/testrocks">Try something new!</a></li>';
echo '<!-- TODO: ADD DEV PAGE FOR DOCUMENTATION OF API -->';
echo '</ul>';
echo '<ul class="pickers yt-uix-button-group" data-button-toggle-group="optional">';
echo '<li>';
echo 'Language:';
echo '<button type="button" class=" yt-uix-button yt-uix-button-text" onclick=";return false;" data-button-toggle="true" data-picker-position="footer" data-button-menu-id="arrow-display" data-picker-key="language" data-button-action="yt.www.picker.load" role="button"><span class="yt-uix-button-content">English </span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""></button>';
echo '</li>';
echo '<li>';
echo 'Location:';
echo '<button type="button" class=" yt-uix-button yt-uix-button-text" onclick=";return false;" data-button-toggle="true" data-picker-position="footer" data-button-menu-id="arrow-display" data-picker-key="country" data-button-action="yt.www.picker.load" role="button"><span class="yt-uix-button-content">Worldwide </span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""></button>';
echo '</li>';
echo '</ul>';
echo '<div id="yt-picker-language-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="">';
echo 'Loading...';
echo '</p>';
echo '</div>';
echo '<div id="yt-picker-country-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="">';
echo 'Loading...';
echo '</p>';
echo '</div>';
echo '<div id="yt-picker-safetymode-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="">';
echo 'Loading...';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- end footer -->';
echo '</div>';
echo '<div id="playlist-bar" class="hid passive editable"';
echo 'data-video-url="/watch?v=&amp;feature=BFql&amp;playnext=1&amp;list=QL" data-list-id="" data-list-type="QL">';
echo '<div id="playlist-bar-bar-container">';
echo '<div id="playlist-bar-bar">';
echo '<div class="yt-alert yt-alert-naked yt-alert-success hid " id="playlist-bar-notifications">';
echo '<div class="yt-alert-icon">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="icon master-sprite"';
echo 'alt="Alert icon">';
echo '</div>';
echo '<div class="yt-alert-content" role="alert"></div>';
echo '</div>';
echo '<span id="playlist-bar-info"><span class="playlist-bar-active playlist-bar-group"><button';
echo 'onclick=";return false;" title="Previous video" type="button"';
echo 'id="playlist-bar-prev-button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-default yt-uix-tooltip yt-uix-button-empty"';
echo 'role="button"><span class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-prev"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="Previous video"><span';
echo 'class="yt-valign-trick"></span></span></button><span';
echo 'class="playlist-bar-count"><span class="playing-index">0</span> / <span';
echo 'class="item-count">0</span></span><button type="button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-default yt-uix-button-empty"';
echo 'onclick=";return false;" id="playlist-bar-next-button" role="button"><span';
echo 'class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-next"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""><span';
echo 'class="yt-valign-trick"></span></span></button></span><span';
echo 'class="playlist-bar-active playlist-bar-group"><button type="button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-default yt-uix-button-empty"';
echo 'onclick=";return false;" id="playlist-bar-autoplay-button" data-button-toggle="true"';
echo 'role="button"><span class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-autoplay"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""><span';
echo 'class="yt-valign-trick"></span></span></button><button type="button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-default yt-uix-button-empty"';
echo 'onclick=";return false;" id="playlist-bar-shuffle-button" data-button-toggle="true"';
echo 'role="button"><span class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-shuffle"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""><span';
echo 'class="yt-valign-trick"></span></span></button></span><span';
echo 'class="playlist-bar-passive playlist-bar-group"><button onclick=";return false;"';
echo 'title="Play videos" type="button" id="playlist-bar-play-button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-default yt-uix-tooltip yt-uix-button-empty"';
echo 'role="button"><span class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-play"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="Play videos"><span';
echo 'class="yt-valign-trick"></span></span></button><span';
echo 'class="playlist-bar-count"><span class="item-count">0</span></span></span><span';
echo 'id="playlist-bar-title" class="yt-uix-button-group"><span class="playlist-title">Unsaved';
echo 'Playlist</span></span></span>';
echo '<a id="playlist-bar-lists-back" href="#">';
echo 'Return to active list';
echo '</a>';
echo '<span id="playlist-bar-controls"><span class="playlist-bar-group"><button type="button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked  yt-uix-button yt-uix-button-text yt-uix-button-empty"';
echo 'onclick=";return false;" id="playlist-bar-toggle-button" role="button"><span';
echo 'class="yt-uix-button-icon-wrapper"><img';
echo 'class="yt-uix-button-icon yt-uix-button-icon-playlist-bar-toggle"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""><span';
echo 'class="yt-valign-trick"></span></span></button></span><span';
echo 'class="playlist-bar-group"><button type="button"';
echo 'class="yt-uix-tooltip yt-uix-tooltip-masked yt-uix-button-reverse flip yt-uix-button yt-uix-button-text"';
echo 'onclick=";return false;" data-button-menu-id="playlist-bar-options-menu"';
echo 'data-button-has-sibling-menu="true" role="button"><span';
echo 'class="yt-uix-button-content">Options </span><img class="yt-uix-button-arrow"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt=""></button></span></span>';
echo '</div>';
echo '</div>';
echo '<div id="playlist-bar-tray-container">';
echo '<div id="playlist-bar-tray" class="yt-uix-slider yt-uix-slider-fluid">';
echo '<button class="yt-uix-button playlist-bar-tray-button yt-uix-button-default yt-uix-slider-prev"';
echo 'onclick="return false;"><img class="yt-uix-slider-prev-arrow"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="Previous video"></button><button';
echo 'class="yt-uix-button playlist-bar-tray-button yt-uix-button-default yt-uix-slider-next"';
echo 'onclick="return false;"><img class="yt-uix-slider-next-arrow"';
echo 'src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="Next video"></button>';
echo '<div class="yt-uix-slider-body">';
echo '<div id="playlist-bar-tray-content" class="yt-uix-slider-slide">';
echo '<ol class="video-list"></ol>';
echo '<ol id="playlist-bar-help">';
echo '<li class="empty playlist-bar-help-message">Your queue is empty. Add videos to your';
echo 'queue using this button: <img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif"';
echo 'class="addto-button-help"><br> or <a';
echo 'href="https://accounts.google.com/ServiceLogin?passive=true&amp;continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26feature%3Dplaylist%26nomobiletemp%3D1%26hl%3Den_US%26next%3D%252Fvideos%253Ffeature%253Dmh&amp;uilel=3&amp;hl=en_US&amp;service=youtube">sign';
echo 'in</a> to load a different list.</li>';
echo '</ol>';
echo '</div>';
echo '<div class="yt-uix-slider-shade-left"></div>';
echo '<div class="yt-uix-slider-shade-right"></div>';
echo '</div>';
echo '</div>';
echo '<div id="playlist-bar-save"></div>';
echo '<div id="playlist-bar-lists" class="dark-lolz"></div>';
echo '<div id="playlist-bar-loading"><img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif"';
echo 'alt="Loading..."><span id="playlist-bar-loading-message">Loading...</span><span';
echo 'id="playlist-bar-saving-message" class="hid">Saving...</span></div>';
echo '<div id="playlist-bar-template" style="display: none;"';
echo 'data-video-thumb-url="//i4.ytimg.com/vi/__video_encrypted_id__/default.jpg">';
echo '<!--<li class="playlist-bar-item yt-uix-slider-slide-unit __classes__" data-video-id="__video_encrypted_id__"><a href="__video_url__" title="__video_title__" class="yt-uix-sessionlink" data-sessionlink="ei=CPjwu5ji3bICFS4RIQod9j-M-A%3D%3D&amp;feature=BFa"><span class="video-thumb ux-thumb yt-thumb-default-106 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img src="http://s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="__video_title__" data-thumb-manual="true" data-thumb="__video_thumb_url__" width="106" ><span class="vertical-align"></span></span></span></span><span class="screen"></span><span class="count"><strong>__list_position__</strong></span><span class="play"><img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif"></span><span class="yt-uix-button yt-uix-button-default delete"><img class="yt-uix-button-icon-playlist-bar-delete" src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" alt="Delete"></span><span class="now-playing">Now playing</span><span dir="ltr" class="title"><span>__video_title__  <span class="uploader">by __video_display_name__</span>';
echo '</span></span><span class="dragger"></span></a></li>-->';
echo '</div>';
echo '<div id="playlist-bar-next-up-template" style="display: none;">';
echo '<!--<div class="playlist-bar-next-thumb"><span class="video-thumb ux-thumb yt-thumb-default-74 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img src="//i4.ytimg.com/vi/__video_encrypted_id__/default.jpg" alt="Thumbnail" width="74" ><span class="vertical-align"></span></span></span></span></div>-->';
echo '</div>';
echo '</div>';
echo '<div id="playlist-bar-options-menu" class="hid">';
echo '<div id="playlist-bar-extras-menu">';
echo '<ul>';
echo '<li><span class="yt-uix-button-menu-item" data-action="clear">';
echo 'Clear all videos from this list';
echo '</span>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<ul>';
echo '<li><span class="yt-uix-button-menu-item"';
echo 'onclick="window.location.href='//support.google.com/youtube/bin/answer.py?answer=146749&amp;hl=en-US'">Learn';
echo 'more</span></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div id="shared-addto-watch-later-login" class="hid">';
echo '<a href="https://accounts.google.com/ServiceLogin?passive=true&amp;continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26feature%3Dplaylist%26nomobiletemp%3D1%26hl%3Den_US%26next%3D%252Fvideos%253Ffeature%253Dmh&amp;uilel=3&amp;hl=en_US&amp;service=youtube"';
echo 'class="sign-in-link">Sign in</a> to add this to a playlist';
echo '</div>';
echo '<div id="shared-addto-menu" style="display: none;" class="hid sign-in">';
echo '<div class="addto-menu">';
echo '<div id="addto-list-panel" class="menu-panel active-panel">';
echo '<span class="yt-uix-button-menu-item yt-uix-tooltip sign-in" data-possible-tooltip=""';
echo 'data-tooltip-show-delay="750"><a';
echo 'href="https://accounts.google.com/ServiceLogin?passive=true&amp;continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26feature%3Dplaylist%26nomobiletemp%3D1%26hl%3Den_US%26next%3D%252Fvideos%253Ffeature%253Dmh&amp;uilel=3&amp;hl=en_US&amp;service=youtube"';
echo 'class="sign-in-link">Sign in</a> to add this to a playlist';
echo '</span>';
echo '</div>';
echo '<div id="addto-list-saved-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<div class="yt-alert yt-alert-naked yt-alert-success  ">';
echo '<div class="yt-alert-icon">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="icon master-sprite"';
echo 'alt="Alert icon">';
echo '</div>';
echo '<div class="yt-alert-content" role="alert">';
echo '<span class="yt-alert-vertical-trick"></span>';
echo '<div class="yt-alert-message">';
echo '<span class="message">Added to <span';
echo 'class="addto-title yt-uix-tooltip yt-uix-tooltip-reverse"';
echo 'title="More information about this playlist"';
echo 'data-tooltip-show-delay="750"></span></span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="addto-list-error-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif">';
echo '<span class="error-details"></span>';
echo '<a class="show-menu-link">Back to list</a>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-input-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<div class="yt-alert yt-alert-naked yt-alert-success  ">';
echo '<div class="yt-alert-icon">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="icon master-sprite"';
echo 'alt="Alert icon">';
echo '</div>';
echo '<div class="yt-alert-content" role="alert">';
echo '<span class="yt-alert-vertical-trick"></span>';
echo '<div class="yt-alert-message">';
echo '<span class="message">Added to playlist:</span>';
echo '<span class="addto-title yt-uix-tooltip"';
echo 'title="More information about this playlist"';
echo 'data-tooltip-show-delay="750"></span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="yt-uix-char-counter" data-char-limit="150">';
echo '<div class="addto-note-box addto-text-box"><textarea id="addto-note"';
echo 'class="addto-note yt-uix-char-counter-input" maxlength="150"></textarea><label';
echo 'for="addto-note" class="addto-note-label">Add an optional note</label></div>';
echo '<span class="yt-uix-char-counter-remaining">150</span>';
echo '</div>';
echo '<button disabled="disabled" type="button"';
echo 'class="playlist-save-note yt-uix-button yt-uix-button-default" onclick=";return false;"';
echo 'role="button"><span class="yt-uix-button-content">Add note </span></button>';
echo '</div>';
echo '<div id="addto-note-saving-panel" class="menu-panel">';
echo '<div class="panel-content loading-content">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif">';
echo '<span>Saving note...</span>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-saved-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif">';
echo '<span class="message">Note added to:</span>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-error-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif">';
echo '<span class="message">Error adding note:</span>';
echo '<ul class="error-details"></ul>';
echo '<a class="add-note-link">Click to add a new note</a>';
echo '</div>';
echo '</div>';
echo '<div class="close-note hid">';
echo '<img src="//s.ytimg.com/yt/img/pixel-vfl3z5WfW.gif" class="close-button">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- end pagebottom -->';
echo '</div>';
echo '<!-- end page -->';
echo '<script id="www-core-js" src="/yt/jsbin/www-core-vfl1pq97W.js" data-loaded="true"></script>';
echo '<script id="www-core-js" src="/yt/jsbin/www-core-vfl1pq97W.js" data-loaded="true"></script>';
echo '<script>yt.www.thumbnaildelayload.init(0);</script>';
echo '<script>';
echo 'yt.setMsg({';
echo ''LIST_CLEARED': "List cleared",';
echo ''PLAYLIST_VIDEO_DELETED': "Video deleted.",';
echo ''ERROR_OCCURRED': "Sorry, an error occurred.",';
echo ''NEXT_VIDEO_TOOLTIP': "Next video:\u003cbr\u003e \u0026#8220;${next_video_title}\u0026#8221;",';
echo ''NEXT_VIDEO_NOTHUMB_TOOLTIP': "Next video",';
echo ''SHOW_PLAYLIST_TOOLTIP': "Show playlist",';
echo ''HIDE_PLAYLIST_TOOLTIP': "Hide playlist",';
echo ''AUTOPLAY_ON_TOOLTIP': "Turn autoplay off",';
echo ''AUTOPLAY_OFF_TOOLTIP': "Turn autoplay on",';
echo ''SHUFFLE_ON_TOOLTIP': "Turn shuffle off",';
echo ''SHUFFLE_OFF_TOOLTIP': "Turn shuffle on",';
echo ''PLAYLIST_BAR_PLAYLIST_SAVED': "Playlist saved!",';
echo ''PLAYLIST_BAR_ADDED_TO_FAVORITES': "Added to favorites",';
echo ''PLAYLIST_BAR_ADDED_TO_PLAYLIST': "Added to playlist",';
echo ''PLAYLIST_BAR_ADDED_TO_QUEUE': "Added to queue",';
echo ''AUTOPLAY_WARNING1': "Next video starts in 1 second...",';
echo ''AUTOPLAY_WARNING2': "Next video starts in 2 seconds...",';
echo ''AUTOPLAY_WARNING3': "Next video starts in 3 seconds...",';
echo ''AUTOPLAY_WARNING4': "Next video starts in 4 seconds...",';
echo ''AUTOPLAY_WARNING5': "Next video starts in 5 seconds...",';
echo ''UNDO_LINK': "Undo"';
echo '});';
echo '';
echo '';
echo 'yt.setConfig({';
echo ''DRAGDROP_BINARY_URL': "\/\/s.ytimg.com\/yt\/jsbin\/www-dragdrop-vflWKaUyg.js",';
echo ''PLAYLIST_BAR_PLAYING_INDEX': -1';
echo '});';
echo '';
echo 'yt.setAjaxToken('addto_ajax_logged_out', "rmWO31ZGdmAjKQm23MH57ZskA6Z8MTM0OTExMDQ0NkAxMzQ5MDI0MDQ2");';
echo '';
echo 'yt.pubsub.subscribe('init', yt.www.lists.init);';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo 'yt.setConfig({ 'SBOX_JS_URL': "\/\/s.ytimg.com\/yt\/jsbin\/www-searchbox-vflsHyn9f.js", 'SBOX_SETTINGS': { "CLOSE_ICON_URL": "\/\/s.ytimg.com\/yt\/img\/icons\/close-vflrEJzIW.png", "SHOW_CHIP": false, "PSUGGEST_TOKEN": null, "REQUEST_DOMAIN": "us", "EXPERIMENT_ID": -1, "SESSION_INDEX": null, "HAS_ON_SCREEN_KEYBOARD": false, "CHIP_PARAMETERS": {}, "REQUEST_LANGUAGE": "en" }, 'SBOX_LABELS': { "SUGGESTION_DISMISS_LABEL": "Dismiss", "SUGGESTION_DISMISSED_LABEL": "Suggestion dismissed" } });';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</script>';
echo '<script>';
echo 'yt.setMsg({';
echo ''ADDTO_WATCH_LATER_ADDED': "Added",';
echo ''ADDTO_WATCH_LATER_ERROR': "Error"';
echo '});';
echo '</script>';
echo '</body>';
echo '';
echo '</html>';
?>