<?php
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<html lang="en"><head>';
echo '<script id="js-528919983" src="/yts/jsbin/www-core-vflG1GmWt.js" data-loaded="true"></script>';
echo '<script id="js-1576221815" src="/yts/jsbin/www-guide-vflDWtzlu.js" data-loaded="true"></script>';
echo '<script id="js-3726928039" src="/yts/jsbin/www-home-vflVATumV.js" data-loaded="true"></script>';
echo '<script id="js-1128033138" src="/yts/jsbin/www-guidev2-vflxw2ZhL.js" data-loaded="true"></script>';
echo '<script async src="/pagead/js/adsbysoogle.js?client=ca-pub-1393483403065318" crossorigin="anonymous"></script>';
echo '<script id="js-1129185537" src="/yts/jsbin/www-home-vflsY_7pm.js" data-loaded="true"></script>';
echo '<script>';
echo 'var yt = yt || {};yt.timing = yt.timing || {};yt.timing.data_ = yt.timing.data_ || {};yt.timing.tick = function(label, opt_time) {var timer = yt.timing.data_['timer'] || {};if(opt_time) {timer[label] = opt_time;}else {timer[label] = new Date().getTime();}yt.timing.data_['timer'] = timer;};yt.timing.info = function(label, value) {var info_args = yt.timing.data_['info_args'] || {};info_args[label] = value;yt.timing.data_['info_args'] = info_args;};yt.timing.info('e', "904000,906373,923014,902553,916613,916708,920704,912806,928001,922403,922405,929901,913605,929104,913546,913556,908496,920201,913302,919009,900816,911116,902554,901451,902556");if (document.webkitVisibilityState == 'prerender') {document.addEventListener('webkitvisibilitychange', function() {yt.timing.tick('start');}, false);}yt.timing.tick('start');yt.timing.info('li','0');try {yt.timing.data_['srt'] = window.gtbExternal && window.gtbExternal.pageT() ||window.external && window.external.pageT;} catch(e) {}if (window.chrome && window.chrome.csi) {yt.timing.data_['srt'] = Math.floor(window.chrome.csi().pageT);}if (window.msPerformance && window.msPerformance.timing) {yt.timing.data_['srt'] = window.msPerformance.timing.responseStart - window.msPerformance.timing.navigationStart;}    </script>';
echo '<title>SubRocks</title><link rel="search" type="application/opensearchdescription+xml" href="/opensearch?locale=en_US" title="SubRocks Video Search"><link rel="alternate" media="handheld" href="/index?&amp;desktop_uri=%2F"><link rel="alternate" media="only screen and (max-width: 640px)" href="/index?&amp;desktop_uri=%2F"><meta name="description" content="Share your videos with friends, family, and the world"><meta name="keywords" content="video, sharing, camera phone, video phone, free, upload"> <meta property="og:image" content="/yt/imgbin/full-size-logo.png">';
echo '<meta property="fb:app_id" content="87741124305">';
echo '<link rel="publisher" href="https://plus.google.com/115229808208707341778">';
echo '<link id="css-2783428260" rel="stylesheet" href="/yts/cssbin/www-hitchhiker-vflTcqmWD.css">';
echo '<link id="css-146112479" rel="stylesheet" href="//s.ytimg.com/yts/cssbin/www-home-c4-vflj7s9Ng.css">';
echo '<script>';
echo 'if (window.yt.timing) {yt.timing.tick("ct");}    </script>';
echo '<style></style><style type="text/css">.gssb_c{border:0;position:absolute;z-index:989}.gssb_e{border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-moz-box-shadow:0 2px 4px rgba(0,0,0,0.2);cursor:default}.gssb_f{visibility:hidden;white-space:nowrap}.gssb_k{border:0;display:block;position:absolute;top:0;z-index:988}.gsdd_a{border:none!important}.gsib_a{width:100%;padding:4px 6px 0}.gsib_a,.gsib_b{vertical-align:top}.gssb_a{padding:0 7px}.gssb_a,.gssb_a td{white-space:nowrap;overflow:hidden;line-height:22px}#gssb_b{font-size:11px;color:#36c;text-decoration:none}#gssb_b:hover{font-size:11px;color:#36c;text-decoration:underline}.gssb_g{text-align:center;padding:8px 0 7px;position:relative}.gssb_h{font-size:15px;height:28px;margin:0.2em}.gssb_i{background:#eee}.gss_ifl{visibility:hidden;padding-left:5px}.gssb_i .gss_ifl{visibility:visible}a.gssb_j{font-size:13px;color:#36c;text-decoration:none;line-height:100%}a.gssb_j:hover{text-decoration:underline}.gssb_l{height:1px;background-color:#e5e5e5}.gssb_m{color:#000;background:#fff}.gscp_a,.gscp_c,.gscp_d,.gscp_e,.gscp_f{display:inline-block;vertical-align:bottom}.gscp_f{border:none}.gscp_a{background:#d9e7fe;border:1px solid #9cb0d8;cursor:default;outline:none;text-decoration:none!important;user-select:none;-moz-user-select:none;}.gscp_a:hover{border-color:#869ec9}.gscp_a.gscp_b{background:#4787ec;border-color:#3967bf}.gscp_c{color:#444;font-size:13px;font-weight:bold}.gscp_d{color:#aeb8cb;cursor:pointer;font:21px arial,sans-serif;line-height:inherit;padding:0 7px}.gscp_d{position:relative;top:1px}.gscp_a:hover .gscp_d{color:#575b66}.gscp_c:hover,.gscp_a .gscp_d:hover{color:#222}.gscp_a.gscp_b .gscp_c,.gscp_a.gscp_b .gscp_d{color:#fff}.gscp_e{height:100%;padding:0 4px}a.gspqs_a{padding:0 3px 0 8px}.gspqs_b{color:#666;line-height:22px}.gspr_a{padding-right:1px}.gsq_a{padding:0}.gsfe_a{border:1px solid #b9b9b9;border-top-color:#a0a0a0;box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);-moz-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);-webkit-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);}.gsfe_b{border:1px solid #4d90fe;outline:none;box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);-moz-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);-webkit-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);}.gsok_a{background:url(data:image/gif;base64,R0lGODlhEwALAKECAAAAABISEv///////yH5BAEKAAIALAAAAAATAAsAAAIdDI6pZ+suQJyy0ocV3bbm33EcCArmiUYk1qxAUAAAOw==) no-repeat center;display:inline-block;height:11px;line-height:0;width:19px}.gsok_a img{border:none;visibility:hidden}.gsst_a{display:inline-block}.gsst_a{cursor:pointer;padding:0 4px}.gsst_a:hover{text-decoration:none!important}.gsst_b{font-size:16px;padding:0 2px;user-select:none;-moz-user-select:none;white-space:nowrap}.gsst_e{opacity:0.55;}.gsst_a:hover .gsst_e,.gsst_a:focus .gsst_e{opacity:0.72;}.gsst_a:active .gsst_e{opacity:1;}.gsst_f{background:white;text-align:left}.gsst_g{background-color:white;border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-moz-box-shadow:0 2px 4px rgba(0,0,0,0.2);margin:-1px -3px;padding:0 6px}.gsst_h{background-color:white;height:1px;margin-bottom:-1px;position:relative;top:-1px}.gsfi{font-size:16px}.gsfs{font-size:16px}a.gssb_j{font-size:12px;color:#03c}.gssb_a,.gssb_a td{line-height:20px}.gssb_a{padding:0 6px}.gssb_c{z-index:3000001}.gssb_i td{background:#eee}.gssb_k{z-index:3000000}.gssb_l{margin:2px 0}.gsib_a{padding:0 4px}.gsok_a{padding:0}.gsok_a img{display:block}.gsfe_b{border:1px solid #1c62b9;box-shadow:inset 0 1px 2px rgba(0,0,0,0.3);-moz-box-shadow:inset 0 1px 2px rgba(0,0,0,0.3);outline:none;}a.gscp_a{position:relative;background:#e2e2e2;border:1px solid #bbb;border-radius:3px}.gsfe_a a.gscp_a{border-width:1px;border-style:solid;border-color:#bbb}a.gscp_a.gscp_b{border-color:#777!important;background:#999;outline:none}.gscp_c{color:#666;font-size:11px;font-weight:bold;padding-right:20px;text-shadow:0 1px 0 rgba(255, 255, 255, 0.5);-ms-filter:"progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80ffffff,Positive=true)";zoom:1;filter:progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80ffffff,Positive=true)}.gsfe_a a.gscp_a .gscp_c{color:#444}a.gscp_a.gscp_b .gscp_c,.gsfe_a a.gscp_a.gscp_b .gscp_c{color:#fff;text-shadow:0 1px 0 rgba(100, 100, 100, 0.5);-ms-filter:"progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80646464,Positive=true)";zoom:1;filter:progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80646464,Positive=true)}.gscp_d{position:absolute;padding:0;background:url(/yts/img/icons/close-vflrEJzIW.png);background-repeat:no-repeat;background-position-y:0;right:3px;top:6px;font-size:0;width:13px;height:13px}.gscp_d:hover{background-position-y:-13px}a.gscp_a.gscp_b .gscp_d{background-position-y:-26px}.gsfe_a a.gscp_a.gscp_b .gscp_d:hover{background-position-y:-39px}.gscp_f{background:#000}</style></head><body dir="ltr" class="  ltr        site-left-aligned    exp-new-site-width exp-watch7-comment-ui hitchhiker-enabled';
echo 'guide-enabled    guide-expanded"><div id="body-container"><form name="logoutForm" method="POST" action="/logout"><input type="hidden" name="action_logout" value="1"><input name="session_token" type="hidden" value="gt1OcUzX0E0XLlUpO_wwn2bX4DB8MTM1NzA4NTU0M0AxMzU2OTk5MTQz"></form>';
echo '<style></style><style type="text/css">.gssb_c{border:0;position:absolute;z-index:989}.gssb_e{border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-moz-box-shadow:0 2px 4px rgba(0,0,0,0.2);cursor:default}.gssb_f{visibility:hidden;white-space:nowrap}.gssb_k{border:0;display:block;position:absolute;top:0;z-index:988}.gsdd_a{border:none!important}.gsib_a{width:100%;padding:4px 6px 0}.gsib_a,.gsib_b{vertical-align:top}.gssb_a{padding:0 7px}.gssb_a,.gssb_a td{white-space:nowrap;overflow:hidden;line-height:22px}#gssb_b{font-size:11px;color:#36c;text-decoration:none}#gssb_b:hover{font-size:11px;color:#36c;text-decoration:underline}.gssb_g{text-align:center;padding:8px 0 7px;position:relative}.gssb_h{font-size:15px;height:28px;margin:0.2em}.gssb_i{background:#eee}.gss_ifl{visibility:hidden;padding-left:5px}.gssb_i .gss_ifl{visibility:visible}a.gssb_j{font-size:13px;color:#36c;text-decoration:none;line-height:100%}a.gssb_j:hover{text-decoration:underline}.gssb_l{height:1px;background-color:#e5e5e5}.gssb_m{color:#000;background:#fff}.gscp_a,.gscp_c,.gscp_d,.gscp_e,.gscp_f{display:inline-block;vertical-align:bottom}.gscp_f{border:none}.gscp_a{background:#d9e7fe;border:1px solid #9cb0d8;cursor:default;outline:none;text-decoration:none!important;user-select:none;-moz-user-select:none;}.gscp_a:hover{border-color:#869ec9}.gscp_a.gscp_b{background:#4787ec;border-color:#3967bf}.gscp_c{color:#444;font-size:13px;font-weight:bold}.gscp_d{color:#aeb8cb;cursor:pointer;font:21px arial,sans-serif;line-height:inherit;padding:0 7px}.gscp_d{position:relative;top:1px}.gscp_a:hover .gscp_d{color:#575b66}.gscp_c:hover,.gscp_a .gscp_d:hover{color:#222}.gscp_a.gscp_b .gscp_c,.gscp_a.gscp_b .gscp_d{color:#fff}.gscp_e{height:100%;padding:0 4px}a.gspqs_a{padding:0 3px 0 8px}.gspqs_b{color:#666;line-height:22px}.gspr_a{padding-right:1px}.gsq_a{padding:0}.gsfe_a{border:1px solid #b9b9b9;border-top-color:#a0a0a0;box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);-moz-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);-webkit-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.1);}.gsfe_b{border:1px solid #4d90fe;outline:none;box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);-moz-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);-webkit-box-shadow:inset 0px 1px 2px rgba(0,0,0,0.3);}.gsok_a{background:url(data:image/gif;base64,R0lGODlhEwALAKECAAAAABISEv///////yH5BAEKAAIALAAAAAATAAsAAAIdDI6pZ+suQJyy0ocV3bbm33EcCArmiUYk1qxAUAAAOw==) no-repeat center;display:inline-block;height:11px;line-height:0;width:19px}.gsok_a img{border:none;visibility:hidden}.gsst_a{display:inline-block}.gsst_a{cursor:pointer;padding:0 4px}.gsst_a:hover{text-decoration:none!important}.gsst_b{font-size:16px;padding:0 2px;user-select:none;-moz-user-select:none;white-space:nowrap}.gsst_e{opacity:0.55;}.gsst_a:hover .gsst_e,.gsst_a:focus .gsst_e{opacity:0.72;}.gsst_a:active .gsst_e{opacity:1;}.gsst_f{background:white;text-align:left}.gsst_g{background-color:white;border:1px solid #ccc;border-top-color:#d9d9d9;box-shadow:0 2px 4px rgba(0,0,0,0.2);-moz-box-shadow:0 2px 4px rgba(0,0,0,0.2);margin:-1px -3px;padding:0 6px}.gsst_h{background-color:white;height:1px;margin-bottom:-1px;position:relative;top:-1px}.gsfi{font-size:16px}.gsfs{font-size:16px}a.gssb_j{font-size:12px;color:#03c}.gssb_a,.gssb_a td{line-height:20px}.gssb_a{padding:0 6px}.gssb_c{z-index:3000001}.gssb_i td{background:#eee}.gssb_k{z-index:3000000}.gssb_l{margin:2px 0}.gsib_a{padding:0 4px}.gsok_a{padding:0}.gsok_a img{display:block}.gsfe_b{border:1px solid #1c62b9;box-shadow:inset 0 1px 2px rgba(0,0,0,0.3);-moz-box-shadow:inset 0 1px 2px rgba(0,0,0,0.3);outline:none;}a.gscp_a{position:relative;background:#e2e2e2;border:1px solid #bbb;border-radius:3px}.gsfe_a a.gscp_a{border-width:1px;border-style:solid;border-color:#bbb}a.gscp_a.gscp_b{border-color:#777!important;background:#999;outline:none}.gscp_c{color:#666;font-size:11px;font-weight:bold;padding-right:20px;text-shadow:0 1px 0 rgba(255, 255, 255, 0.5);-ms-filter:"progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80ffffff,Positive=true)";zoom:1;filter:progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80ffffff,Positive=true)}.gsfe_a a.gscp_a .gscp_c{color:#444}a.gscp_a.gscp_b .gscp_c,.gsfe_a a.gscp_a.gscp_b .gscp_c{color:#fff;text-shadow:0 1px 0 rgba(100, 100, 100, 0.5);-ms-filter:"progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80646464,Positive=true)";zoom:1;filter:progid:DXImageTransform.Microsoft.dropshadow(OffX=0,OffY=1,Color=#80646464,Positive=true)}.gscp_d{position:absolute;padding:0;background:url(/yts/img/icons/close-vflrEJzIW.png);background-repeat:no-repeat;background-position-y:0;right:3px;top:6px;font-size:0;width:13px;height:13px}.gscp_d:hover{background-position-y:-13px}a.gscp_a.gscp_b .gscp_d{background-position-y:-26px}.gsfe_a a.gscp_a.gscp_b .gscp_d:hover{background-position-y:-39px}.gscp_f{background:#000}</style></head><body dir="ltr" class="  ltr        site-left-aligned    exp-new-site-width exp-watch7-comment-ui hitchhiker-enabled';
echo 'guide-enabled    guide-expanded"><div id="body-container"><form name="logoutForm" method="POST" action="/logout"><input type="hidden" name="action_logout" value="1"><input name="session_token" type="hidden" value="gt1OcUzX0E0XLlUpO_wwn2bX4DB8MTM1NzA4NTU0M0AxMzU2OTk5MTQz"></form> <div id="yt-masthead-container" class="yt-grid-box yt-masthead-hh"><div id="yt-masthead" class=""> <a id="logo-container" href="/" title="SubRocks home"><img id="logo" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="SubRocks home"><span class="content-region"></span></a>';
echo '<div id="yt-masthead-user">';
echo '<span id="yt-masthead-user-displayname" dir="ltr" class="yt-valign-container" onclick="yt.www.masthead.toggleExpandedMasthead();">';
echo 'SilasTheHedgehog </span>';
echo '<button onclick=";return false;" class="sb-notif-off yt-uix-button yt-uix-button-hh-default" type="button" id="sb-button-notify" role="button"><span class="yt-uix-button-content">0</span></button> <button onclick="yt.www.masthead.toggleExpandedMasthead();;return false;" class="yt-masthead-user-icon yt-uix-button yt-uix-button-hh-default" type="button" data-orientation="vertical" role="button"><span class="yt-uix-button-content"> <span class="video-thumb ux-thumb yt-thumb-square-27 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img alt="Thumbnail" src="/dynamic/pfp/60c22450f1e05e7d86747ac12221e801.png" width="27" loading="lazy"><span class="vertical-align"></span></span></span></span>';
echo '</span></button>';
echo '<span id="yt-masthead-dropdown" onclick="yt.www.masthead.toggleExpandedMasthead();"></span>';
echo '</div> <div id="yt-masthead-content"><span class="yt-uix-button-group" id="masthead-upload-button-group"><a href="/my_videos_upload" class="yt-uix-button  start link-gplus-lightbox yt-uix-sessionlink yt-uix-button-hh-default" data-upsell="upload"><span class="yt-uix-button-content">Upload</span></a><button onclick=";return false;" type="button" class="end yt-uix-button yt-uix-button-hh-default yt-uix-button-empty" data-button-menu-id="upload-button-menu" role="button"><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="" loading="lazy"></button></span>';
echo '<ul id="upload-button-menu" class="yt-uix-button-menu yt-uix-button-menu-default" role="menu" aria-haspopup="true" style="display: none"><li role="menuitem"><a href="/my_videos" class="yt-uix-button-menu-item upload-menu-link"><img class="upload-menu-vm" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" loading="lazy">Video Manager</a></li><li role="menuitem"><a href="/analytics" class="yt-uix-button-menu-item upload-menu-link"><img class="upload-menu-analytics" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">Analytics</a></li></ul>';
echo '<form id="masthead-search" class="search-form consolidated-form" action="/results" onsubmit="if (_gel('masthead-search-term').value == '') return false;">';
echo '<button dir="ltr" tabindex="2" type="submit" id="search-btn" class="search-btn-component search-button yt-uix-button yt-uix-button-default" onclick="if (_gel('masthead-search-term').value == '') return false; _gel('masthead-search').submit(); return false;;return true;" role="button"><span class="yt-uix-button-content">Search </span></button>';
echo '';
echo '<div id="masthead-search-terms" class="masthead-search-terms-border" dir="ltr">';
echo '<label>';
echo '<input id="masthead-search-term" class="search-term" name="search_query" value="" type="text" tabindex="1" onkeyup="goog.i18n.bidi.setDirAttribute(event,this)" title="Search"> </label>';
echo '</div>';
echo '</form>';
echo '</div></div></div>';
echo '<div id="masthead-expanded" class="hid" style="display: none;">';
echo '<div id="masthead-expanded-container" class="with-sandbar">';
echo '<div id="masthead-expanded-menus-container">';
echo '<span id="masthead-expanded-menu-shade"></span>';
echo '<div id="masthead-expanded-menu" class="">';
echo '<span class="masthead-expanded-menu-header">';
echo 'SubRocks';
echo '</span>';
echo '<ul id="masthead-expanded-menu-list">';
echo '<li class="masthead-expanded-menu-item">';
echo '<a href="/channel/SilasTheHedgehog?feature=mhee">';
echo 'My channel </a>';
echo '</li>';
echo '<li class="masthead-expanded-menu-item">';
echo '<a href="/my_videos?feature=mhee">';
echo 'Video Μanager </a>';
echo '</li>';
echo '<li class="masthead-expanded-menu-item">';
echo '<a href="/my_subscriptions?feature=mhee">Subscriptions</a>';
echo '</li>';
echo '<li class="masthead-expanded-menu-item">';
echo '<a href="/account?feature=mhee">';
echo 'SubRocks settings </a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="masthead-expanded-google-menu">';
echo '<span class="masthead-expanded-menu-header">';
echo 'Soogle account </span>';
echo '<div id="masthead-expanded-menu-google-container">';
echo '<div id="masthead-expanded-menu-google-column1">';
echo '<ul>';
echo '<li class="masthead-expanded-menu-item"><a href="https://plus.google.com/u/0/112155883177922175751">Profile</a></li>';
echo '<li class="masthead-expanded-menu-item"><a href="https://plus.google.com/u/0/stream">Soogle+</a></li>';
echo '<li class="masthead-expanded-menu-item"><a href="https://plus.google.com/u/0/settings/privacy">Privacy</a></li>';
echo '<li class="masthead-expanded-menu-item">';
echo '<a href="https://plus.google.com/u/0/settings">';
echo 'Settings </a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div id="masthead-expanded-menu-google-column2">';
echo '<div id="masthead-expanded-menu-account-container">';
echo '<img id="masthead-expanded-menu-gaia-photo" alt="" data-src="/dynamic/pfp/60c22450f1e05e7d86747ac12221e801.png" src="/dynamic/pfp/60c22450f1e05e7d86747ac12221e801.png" loading="lazy">';
echo '<div id="masthead-expanded-menu-account-info" class="email-only">';
echo '<p>SilasTheHedgehog</p>';
echo '<p id="masthead-expanded-menu-email">Email@gmail.com</a></p>';
echo '</div>';
echo '</div>';
echo '<ul>';
echo '<li class="masthead-expanded-menu-item">';
echo '<a class="end" href="#" onclick="document.logoutForm.submit(); return false;">';
echo 'Sign out </a>';
echo '</li>';
echo '<li class="masthead-expanded-menu-item">';
echo '<div class="yt-uix-clickcard masthead-expanded-menu-switch" data-card-class="masthead-card-switch-account">';
echo '<button onclick=";return false;" class="yt-uix-clickcard-target yt-uix-button yt-uix-button-link" type="button" data-orientation="vertical" data-position="rightbottom" role="button"><span class="yt-uix-button-content">Switch account</span></button>';
echo '<div class="yt-uix-clickcard-content">';
echo '<ul id="yt-masthead-multilogin">';
echo '<li>';
echo '<a class="yt-masthead-multilogin-user yt-valign" href="/signin?next=%2Fwatch%3Fv%3D6Z2WKFDWLn8&amp;authuser=SilasTheHedgehog&amp;action_handle_signin=true">';
echo '<span class="video-thumb ux-thumb yt-thumb-square-46 yt-masthead-multilogin-user-icon"><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img alt="SilasTheHedgehog" src="/dynamic/pfp/60c22450f1e05e7d86747ac12221e801.png" width="46"><span class="vertical-align"></span></span></span></span>';
echo '<span class="yt-masthead-multilogin-user-content yt-valign-container">';
echo '<span class="yt-masthead-multilogin-user-link" dir="ltr">SilasTheHedgehog</span><br>';
echo '<span class="__cf_email__" data-cfemail="054068646c69456268646c692b666a68">Email@gmail.com</span> </span>';
echo '<span class="yt-valign-trick"></span>';
echo '<div class="yt-alert yt-alert-naked yt-alert-success">';
echo '<div class="yt-alert-icon">';
echo '<img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="icon master-sprite" alt="Alert icon" loading="lazy">';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '<div id="yt-masthead-multilogin-actions" class="yt-grid-box">';
echo '<button onclick="document.logoutForm.submit();return false;" id="yt-masthead-multilogin-sign-out" type="button" class=" yt-uix-button yt-uix-button-link" role="button"><span class="yt-uix-button-content">Sign out </span></button>';
echo '<a href="/AddSession?passive=false&amp;service=subrocks&amp;uilel=0&amp;continue=https%3A%2F%2Frblx2023.serv00.net%2Fsignin%3Faction_handle_signin%3Dtrue%26authuser%3D-1%26hl%3Den_US%26next%3D%252Fwatch%253Fv%253D6Z2WKFDWLn8%26nomobiletemp%3D1&amp;hl=en_US">Add account</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="masthead-expanded-sandbar">';
echo '<div id="masthead-expanded-lists-container">';
echo '<div id="masthead-expanded-lists-container">';
echo '<div class="yt-uix-slider yt-uix-slider-at-head">';
echo '<div class="yt-uix-slider yt-rounded" id="masthead-expanded-lists-content" data-slider-slide-selected="2" data-slider-slides="2">';
echo '<button class="yt-uix-button yt-uix-button-default yt-uix-slider-prev" rel="prev"><img class="yt-uix-slider-prev-arrow" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="previous"></button>';
echo '<button class="yt-uix-button yt-uix-button-default yt-uix-slider-next" rel="next"><img class="yt-uix-slider-next-arrow" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="next"></button>';
echo '<div id="masthead-expanded-lists-content" class="yt-uix-slider-body context-data-container">';
echo '<div class="yt-uix-slider-slides">';
echo '<ul class="yt-uix-slider-slide yt-uix-slider-list">';
echo '<li class="playlist-bar-item yt-uix-slider-slide-item ">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/favorites" title="Favorites">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Favorites</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_fav.jpg" data-thumb="/yts/img/pbar_fav.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '<div class="play-all"><img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="play-arrow ">Play all</div>';
echo '</span>';
echo '</a>';
echo '</li>';
echo '<li class="playlist-bar-item yt-uix-slider-item">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/watch_later" title="Watch Later">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Watch Later</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_wl.jpg" data-thumb="/yts/img/pbar_wl.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '<div class="play-all"><img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="play-arrow ">Play all</div>';
echo '</span>';
echo '</a>';
echo '</li>     <li class="playlist-bar-item yt-uix-slider-item">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/likes" title="Likes">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Likes</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_like.jpg" data-thumb="/yts/img/pbar_like.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '</span>';
echo '</a>';
echo '</li>';
echo '';
echo '<li id="howto-addto" class="playlist-bar-item yt-uix-slider-slide-item yt-uix-slider-item">';
echo '<p>To add a video to a playlist, use the "Add to" button below the video player.</p>';
echo '</li>';
echo '</ul>';
echo '<div class="yt-uix-slider-shade-left"></div>';
echo '<div class="yt-uix-slider-shade-right"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="masthead-expanded-lists-container">';
echo '<div class="yt-uix-slider yt-uix-slider-at-head">';
echo '<div class="yt-uix-slider yt-rounded" id="masthead-expanded-lists-content" data-slider-slide-selected="2" data-slider-slides="2">';
echo '<button class="yt-uix-button yt-uix-button-default yt-uix-slider-prev" rel="prev"><img class="yt-uix-slider-prev-arrow" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="previous"></button>';
echo '<button class="yt-uix-button yt-uix-button-default yt-uix-slider-next" rel="next"><img class="yt-uix-slider-next-arrow" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="next"></button>';
echo '<div id="masthead-expanded-lists-content" class="yt-uix-slider-body context-data-container">';
echo '<div class="yt-uix-slider-slides">';
echo '<ul class="yt-uix-slider-slide yt-uix-slider-list">';
echo '<li class="playlist-bar-item yt-uix-slider-slide-item ">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/favorites" title="Favorites">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Favorites</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_fav.jpg" data-thumb="/yts/img/pbar_fav.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '<div class="play-all"><img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="play-arrow ">Play all</div>';
echo '</span>';
echo '</a>';
echo '</li>';
echo '<li class="playlist-bar-item yt-uix-slider-item">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/watch_later" title="Watch Later">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Watch Later</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_wl.jpg" data-thumb="/yts/img/pbar_wl.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '<div class="play-all"><img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="play-arrow ">Play all</div>';
echo '</span>';
echo '</a>';
echo '</li>     <li class="playlist-bar-item yt-uix-slider-item">';
echo '<a data-sessionlink="ei=CIm1_t3R87MCFQaDRAodZhDYCQ%3D%3D&amp;feature=BFa" class="yt-uix-sessionlink playlist-thumb-section" href="/feed/likes" title="Likes">';
echo '<span class="yt-uix-simple-thumb-wrap yt-thumb-160 "><span class="playlist-data-section"><span class="list-video-count">0</span><span class="playlist-data-item-title list-title">Likes</span></span><img data-thumb-manual="true" src="https://vapblox.tk/yts/img/pbar_like.jpg" data-thumb="/yts/img/pbar_like.jpg" width="160"><span class="yt-thumb-clip" style="display: none;"><span class="yt-thumb-clip-inner"><span class="vertical-align"></span></span></span></span>';
echo '<span class="screen video-actions">';
echo '</span>';
echo '</a>';
echo '</li>';
echo '';
echo '<li id="howto-addto" class="playlist-bar-item yt-uix-slider-slide-item yt-uix-slider-item">';
echo '<p>To add a video to a playlist, use the "Add to" button below the video player.</p>';
echo '</li>';
echo '</ul>';
echo '<div class="yt-uix-slider-shade-left"></div>';
echo '<div class="yt-uix-slider-shade-right"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div></div></div></div></div>';
echo '</div>';
echo '<div class="clear"></div>';
echo '</div>';
echo '</div>';
echo '<div id="alerts">';
echo '</div>';
echo '<div id="header">';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<div id="ad_creative_1" class="ad-div mastad" style="z-index: 1;"><a title="" href="https://www.discover.com/"><img src="https://cdn.discordapp.com/attachments/1135396723997540453/1135792686700433489/discoverad.jpg" height="250" width="970" loading="lazy"></a></div><div id="page-container"><div id="page" class="  home     branded-page-v2-detached-top ">';
echo '<div id="guide"> <div id="guide-container">';
echo '<div id="guide-main" class="guide-module  yt-uix-clickcard" data-orientation="vertical" data-position="bottomright" data-force-position="true" data-click-outside-persists="true" data-card-class="watch7-card-promo">';
echo '<div class="guide-module-content ">';
echo '<div id="gh-personal" class="guide-section guide-header">';
echo '<div class="guide-item-container personal-item">';
echo '<h3>';
echo '<a href="/feed/SilasTheHedgehog?feature=guide" class="guide-item  narrow-item" data-channel-id="wkS9GwZYiEvGA0LKWvNOJzpt" data-upsell="guide">';
echo '<span class="display-name">SilasTheHedgehog</span>';
echo '</a>';
echo '</h3>';
echo '<ul class="guide-user-links yt-box">';
echo '<li id="watch-later-guide-item" data-notification-text="Watch Later updated">';
echo '<a class="guide-item " href="/feed/watch_later" data-channel-id="watch_later">';
echo 'Watch Later </a>';
echo '</li>';
echo '<li>';
echo '<a class="guide-item " href="/feed/history" data-channel-id="history">';
echo 'Watch History </a>';
echo '</li>';
echo '<li id="playlists-guide-item" data-notification-text="Playlist updated">';
echo '<a class="guide-item " href="/feed/playlists">';
echo 'Playlists </a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<hr class="guide-section-separator">';
echo '<ul class="guide-toplevel">';
echo '<li class="guide-section guide-static-section guide-section-no-counts">';
echo '<ul class="guide-item-container guide-system-feeds">';
echo '<li>';
echo '<a class="guide-item " href="/home" data-channel-id="highlights">';
echo '<span class="display-name" title="What to watch">';
echo 'What to watch </span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a class="guide-item " href="/feed/subscriptions" data-channel-id="subscriptions">';
echo '<span class="display-name" title="My subscriptions">';
echo 'My subscriptions </span>';
echo '</a>';
echo '</li>';
echo '<li>';
echo '<a class="guide-item " href="/feed/social" data-channel-id="social">';
echo '<span class="display-name" title="Social">';
echo 'Social </span>';
echo '</a>';
echo '</li>';
echo '</ul>';
echo '<hr class="guide-section-separator">';
echo '</li>';
echo '<li id="guide-subscriptions-section" class="guide-section without-filter">';
echo '<span class="guide-sort-container yt-uix-button-group"><button onclick=";return false;" class="guide-sort-button flip yt-uix-button yt-uix-button-guide-sorts yt-uix-button-short yt-uix-button-empty" type="button" data-guide-sort="None" data-button-has-sibling-menu="true" role="button" aria-pressed="false" aria-expanded="false" aria-haspopup="true" aria-activedescendant=""><img class="yt-uix-button-arrow" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><ul class=" yt-uix-button-menu yt-uix-button-menu-guide-sorts" role="menu" aria-haspopup="true" style="display: none;"><li role="menuitem" id="aria-id-69527611834"><span onclick=";return false;" class="guide-sort-choice checked yt-uix-button-menu-item" data-guide-sort="0">Most Relevant</span></li><li role="menuitem" id="aria-id-85523631953"><span onclick=";return false;" class="guide-sort-choice yt-uix-button-menu-item" data-guide-sort="1">New Activity</span></li><li role="menuitem" id="aria-id-86579535102"><span onclick=";return false;" class="guide-sort-choice yt-uix-button-menu-item" data-guide-sort="2">A-Z</span></li></ul></button></span>';
echo '<h3>Subscriptions</h3>';
echo '<div id="guide-subs-footer-container">';
echo '<div id="guide-subscriptions-container">';
echo '<div class="guide-channels-content">';
echo '<ul id="guide-channels" class="guide-channels-list guide-item-container yt-uix-scroller filter-has-matches">';
echo '';
echo '<li class="guide-channel">';
echo '<a class="guide-item " href="/feed/test" title="test" data-channel-id="test">';
echo '<span class="thumb"><span class="video-thumb ux-thumb yt-thumb-square-18 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img data-group-key="guide-channel-thumbs" data-thumb="/dynamic/pfp/default.png" data-thumb-manual="1" alt="Thumbnail" src="/dynamic/pfp/default.png" width="18"><span class="vertical-align"></span></span></span></span></span>';
echo '<span class="display-name">';
echo '<span>test</span>';
echo '</span>';
echo '</a>';
echo '</li>';
echo '<li class="guide-channel">';
echo '<a class="guide-item " href="/feed/SubRocks" title="SubRocks" data-channel-id="SubRocks">';
echo '<span class="thumb"><span class="video-thumb ux-thumb yt-thumb-square-18 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img data-group-key="guide-channel-thumbs" data-thumb="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" data-thumb-manual="1" alt="Thumbnail" src="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" width="18"><span class="vertical-align"></span></span></span></span></span>';
echo '<span class="display-name">';
echo '<span>SubRocks</span>';
echo '</span>';
echo '</a>';
echo '</li>';
echo '<li id="guide-filter-no-results">';
echo 'No channels found';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<hr class="guide-section-separator">';
echo '<div id="gh-management" class="guide-management">';
echo '<div class="guide-item-container">';
echo '<a href="/channels?feature=guide" class="guide-item ">';
echo '<span class="thumb guide-management-plus-icon">';
echo '<img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="">';
echo '</span>';
echo '<span class="guide-management-caption">';
echo 'Browse channels </span>';
echo '</a>';
echo '<a href="/subscription_manager?feature=guide" class="guide-item ">';
echo '<span class="thumb guide-management-settings-icon">';
echo '<img src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="">';
echo '</span>';
echo '<span class="guide-management-caption">';
echo 'Manage subscriptions </span>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '<div class="watch7-card-promo-content yt-uix-clickcard-content">';
echo '<h3 class="watch7-card-promo-header">';
echo '<img class="watch7-card-promo-guide-icon" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo 'This is your guide </h3>';
echo '<div class="watch7-card-promo-message">';
echo 'Access your channel, playlists, subscriptions, and more. </div>';
echo '<div class="watch7-card-promo-account-line">';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-primary" type="button" data-button-action="yt.www.guidev2.watch.acceptPromo" role="button"><span class="yt-uix-button-content">Got it! </span></button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="watch-context-container" class="guide-module hid  collapsed yt-uix-clickcard" data-orientation="vertical" data-position="bottomright" data-force-position="true" data-click-outside-persists="true" data-card-class="watch7-card-promo">';
echo '<div class="watch7-card-promo-content yt-uix-clickcard-content">';
echo '<h3 class="watch7-card-promo-header">';
echo '<img class="watch7-card-promo-context-icon" src="https://s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo 'Never get lost';
echo '</h3>';
echo '<div class="watch7-card-promo-message">';
echo 'Browse videos from the previous page, including the homepage feed, channel videos and search results.';
echo '</div>';
echo '<div class="watch7-card-promo-account-line">';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-primary" type="button" data-button-action="yt.www.guidev2.watch.acceptPromo" role="button"><span class="yt-uix-button-content">Got it! </span></button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div><div id="content">';
echo '<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script id="js-528919983" src="/yts/jsbin/www-core-vflG1GmWt.js" data-loaded="true"></script>';
echo '<script id="js-1576221815" src="/yts/jsbin/www-guide-vflDWtzlu.js" data-loaded="true"></script>';
echo '<script id="js-3726928039" src="/yts/jsbin/www-home-vflVATumV.js" data-loaded="true"></script>';
echo '<script id="js-1128033138" src="/yts/jsbin/www-guidev2-vflxw2ZhL.js" data-loaded="true"></script>';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>';
echo '<div class="branded-page-v2-container enable-fancy-subscribe-button ">';
echo '<div class="branded-page-v2-col-container clearfix">';
echo '<div class="branded-page-v2-secondary-col">';
echo '<div class="branded-page-related-channels branded-page-gutter-padding">';
echo '<h2 class="branded-page-related-channels-title" dir="ltr">';
echo 'Recommended Channels';
echo '</h2>';
echo '<ul class="branded-page-related-channels-list">';
echo '<li class="guide-channel">';
echo '<li class="branded-page-related-channels-item clearfix" data-external-id="UC3FEiYmIZrqsZo5F-wKjj1d">';
echo '<a href="/user/SubRocks" class="spf-link yt-uix-sessionlink">';
echo '<span class="video-thumb ux-thumb yt-thumb-square-32 branded-page-related-channels-thumb"><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img alt="Thumbnail" src="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" width="32" data-group-key="thumb-group-0"><span class="vertical-align"></span></span></span></span>';
echo '</a>';
echo '<div class="branded-page-related-channels-content">';
echo '<h3>';
echo '<a class="spf-link yt-uix-tooltip yt-uix-sessionlink " href="/user/SubRocks" dir="ltr">';
echo '<span class="qualified-channel-title" title="SubRocks"><span class="qualified-channel-title-inner">SubRocks</span></span><span class="qualified-channel-title-badge"></span>';
echo '</a>';
echo '</h3>';
echo '<span class=" yt-uix-button-subscription-container yt-uix-button-context-light"><button onclick="subscribe(';
echo ''SubRocks',';
echo ''0981c2a0dfb76e70b4117fd2c991ece1.png',';
echo ''',';
echo 'this';
echo ');" type="button" class=" yt-uix-button hover-enabled yt-uix-button-subscribe-unbranded" href="/r/subscribe?n=SubRocks" data-style-type="unbranded" role="button" data-sessionlink="ei=5zAwUZZDlKeEAfqNgaAC&amp;feature=rc-rel"><span class="yt-uix-button-icon-wrapper"> <img class="yt-uix-button-icon yt-uix-button-icon-subscribe-unbranded" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="" title="">';
echo '<span class="yt-uix-button-valign"></span></span><span class="yt-uix-button-content"><span class="subscribe-hh-label">Subscribe</span><span class="subscribed-hh-label">Subscribed</span><span class="unsubscribe-hh-label">Unsubscribe</span> </span></button><span class="yt-subscription-button-subscriber-count-unbranded-horizontal">0</span><span class="yt-subscription-button-disabled-mask"></span></span>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="branded-page-v2-primary-col">';
echo '<div class="branded-page-v2-body" id="gh-activityfeed">';
echo '<div id="feed" class="spf-nolink ">';
echo '<div class="individual-feed" data-loaded="true" data-feed-name="Minecraft" data-feed-type="user" data-filter-type="" data-feed-id="Minecraft">';
echo '<div class="feed-container" data-filter-type="" data-view-type="" data-paging="1355742046">';
echo '<div class="feed-page">';
echo '<ul class="context-data-container">';
echo '<li id="feed-pyv-container" class="feed-item-container   feed-list-item feed-item-container yt-card">';
echo '<strong style="font-size: 20px;">Hi SilasTheHedgehog! This is your SubRocks homepage</strong><br><br>';
echo '<img alt="Joystiq" align="left" role="contentinfo" src="/yts/imgbin/default.png" width="100"><p style="line-height: normal;">&nbsp;&nbsp;&nbsp; Right now your homepage has some popular videos and personalized <br> &nbsp;&nbsp;&nbsp; recommendations, but it could be so much better. It could have videos from your <br> &nbsp;&nbsp;&nbsp; favorite shows, bands, blogs, topics, and more! When you subscribe to channels, <br> &nbsp;&nbsp;&nbsp; you'll see their latest videos here.</p>';
echo '<div class="" style="position:relative;left: 90px;">';
echo '<p style="font-size: 15px;position:relative;left: -373px;top: 30px; text-align: right;" margin="right" right="15">So go add some channels and <br> make this your own</p>';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-primary" style="position:relative;left: 137px;" type="button" data-button-action="yt.www.guidev2.watch.acceptPromo" role="button"><span class="yt-uix-button-content">Get started &#8250; </span></button>';
echo '</div>';
echo '</li><hr style="margin-right: -20px;" class="branded-page-v2-col-container-bottom-border">';
echo '';
echo '<li class="feed-item-container  " data-channel-key="SubRocks">';
echo '<div class="feed-author-bubble-container">';
echo '<a href="/2013/userr/SubRocks?feature=g-crec-u" class="feed-author-bubble   "> <span class="feed-item-author ">';
echo '<span class="video-thumb ux-thumb yt-thumb-square-28 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img alt="SubRocks" src="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" data-thumb="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" width="28"><span class="vertical-align"></span></span></span></span>';
echo '</span>';
echo '</a> </div>';
echo '<div class="feed-item-main">';
echo '<div class="feed-item-header">';
echo '<span class="feed-item-actions-line">';
echo '<span class="feed-item-owner"><a title="SubRocks" dir="ltr" href="/userr/SubRocks?feature=g-crec-u">SubRocks</a></span> uploaded a video';
echo '</span>';
echo '<span class="feed-item-time">';
echo '2023-08-03 04:14:57 </span>';
echo '</div>';
echo '<div class="feed-item-main-content">';
echo '<div class="feed-item-content-wrapper clearfix context-data-item" data-context-item-user="Test" data-context-item-time="0:00" data-context-item-title="Test" data-context-item-views="0 views" data-context-item-id="yUbM57W9CO8" data-context-item-type="video" data-context-item-actionuser="Test">';
echo '<div class="feed-item-thumb">';
echo '<a class="ux-thumb-wrap contains-addto  yt-uix-contextlink yt-uix-sessionlink " data-sessionlink="feature=g-crec-u&amp;ei=COyI797RuLQCFSsWIQod0FCFuQ%3D%3D&amp;ved=CB8Qph4oAA%3D%3D&amp;context=G2cce68eRCGXQYbcTJ33bTQzTvVHkd_lo7_Czp9GgoOmyXwydegvU" href="/2013/watch?v=6HS8Tay8-xgg" tabindex="-1">';
echo '<span class="video-thumb ux-thumb yt-thumb-default-185 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img tabindex="-1" alt="" src="/dynamic/thumbs/6HS8Tay8-xg.png" data-thumb="/dynamic/thumbs/6HS8Tay8-xg.png" width="185" loading="lazy"><span class="vertical-align"></span></span></span></span>';
echo '<span class="video-time">0:18</span>';
echo '<button class="addto-button video-actions spf-nolink addto-watch-later-button yt-uix-button yt-uix-button-default yt-uix-button-short yt-uix-tooltip" type="button" title="Watch Later" onclick=";return false;" data-video-ids="6HS8Tay8-xgg" role="button" data-tooltip-text="Watch Later"><span class="yt-uix-button-content"> <img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="Watch Later">';
echo '</span></button>';
echo '</a>';
echo '</div>';
echo '<div class="feed-item-content">';
echo '<h4>';
echo '<a class="feed-video-title title yt-uix-contextlink  yt-uix-sessionlink" href="/2013/watch?v=6HS8Tay8-xgg" data-sessionlink="feature=g-crec-u&amp;ei=COyI797RuLQCFSsWIQod0FCFuQ%3D%3D&amp;ved=CB8Qph4oAA%3D%3D&amp;context=G2cce68eRCGXQYbcTJ33bTQzTvVHkd_lo7_Czp9GgoOmyXwydegvU">';
echo 'test</a>';
echo '</h4>';
echo '<div class="metadata">';
echo '<span class="view-count">';
echo '6 views </span>';
echo '<div class="description">';
echo '<p></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<span class="feed-item-action-menu subscribed" data-external-id="PS1QXlm4qXKhVwi7EBoM_RGFpwdqVnAH-dqC8OhRcPzV0ngx04EJHgQ==">';
echo '<button type="button" class="flip yt-uix-button yt-uix-button-feed-item-action-menu yt-uix-button-empty" onclick=";return false;" data-button-has-sibling-menu="True" role="button" aria-pressed="false" aria-expanded="false" aria-haspopup="true" aria-activedescendant=""><span class="yt-uix-button-icon-wrapper"><img class="yt-uix-button-icon yt-uix-button-icon-feed-item-action-menu" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><span class="yt-valign-trick"></span></span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><ul class=" yt-uix-button-menu yt-uix-button-menu-feed-item-action-menu" role="menu" aria-haspopup="true" style="display: none;"><li role="menuitem" id="aria-id-17017458839"><span data-action="hide" class="dismiss-menu-choice yt-uix-button-menu-item" onclick=";return false;">Hide this activity</span></li><li role="menuitem" id="aria-id-27652003452"><span data-subscription-id="s-g9bXtaCSKRwzCmeFkvD912YfxX4CmZ5I-IkGd8HUI" data-action="uploads" class="dismiss-menu-choice uploads yt-uix-button-menu-item" onclick=";return false;">Only show uploads from SubRocks</span></li><li role="menuitem" id="aria-id-13786163608"><span data-action="subscribe" class="dismiss-menu-choice subscribe yt-uix-button-menu-item" onclick=";return false;">Subscribe to SubRocks</span></li><li role="menuitem" id="aria-id-88805288643"><span data-channel-key="SubRocks" onclick=";return false;" data-action="unsubscribe" data-subscription-id="s-g9bXtaCSKRwzCmeFkvD912YfxX4CmZ5I-IkGd8HUI" class="dismiss-menu-choice unsubscribe yt-uix-button-menu-item">Unsubscribe from SubRocks</span></li></ul></button>';
echo '</span>';
echo '</div>';
echo '<div class="feed-item-dismissal-notices"><div class="feed-item-dismissal feed-item-dismissal-hide hid">This item has been hidden</div><div class="feed-item-dismissal feed-item-dismissal-uploads hid">In the future you will only see uploads from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-all-activity hid">In the future you will see all activity from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-unsubscribe hid">You have been unsubscribed from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div></div>';
echo '</li>';
echo '<li class="feed-item-container  " data-channel-key="SubRocks">';
echo '<div class="feed-author-bubble-container">';
echo '<a href="/2013/userr/SubRocks?feature=g-crec-u" class="feed-author-bubble   "> <span class="feed-item-author ">';
echo '<span class="video-thumb ux-thumb yt-thumb-square-28 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img alt="SubRocks" src="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" data-thumb="/dynamic/pfp/0981c2a0dfb76e70b4117fd2c991ece1.png" width="28"><span class="vertical-align"></span></span></span></span>';
echo '</span>';
echo '</a> </div>';
echo '<div class="feed-item-main">';
echo '<div class="feed-item-header">';
echo '<span class="feed-item-actions-line">';
echo '<span class="feed-item-owner"><a title="SubRocks" dir="ltr" href="/userr/SubRocks?feature=g-crec-u">SubRocks</a></span> uploaded a video';
echo '</span>';
echo '<span class="feed-item-time">';
echo '2023-08-03 04:14:57 </span>';
echo '</div>';
echo '<div class="feed-item-main-content">';
echo '<div class="feed-item-content-wrapper clearfix context-data-item" data-context-item-user="Test" data-context-item-time="0:00" data-context-item-title="Test" data-context-item-views="0 views" data-context-item-id="yUbM57W9CO8" data-context-item-type="video" data-context-item-actionuser="Test">';
echo '<div class="feed-item-thumb">';
echo '<a class="ux-thumb-wrap contains-addto  yt-uix-contextlink yt-uix-sessionlink " data-sessionlink="feature=g-crec-u&amp;ei=COyI797RuLQCFSsWIQod0FCFuQ%3D%3D&amp;ved=CB8Qph4oAA%3D%3D&amp;context=G2cce68eRCGXQYbcTJ33bTQzTvVHkd_lo7_Czp9GgoOmyXwydegvU" href="/2013/watch?v=6HS8Tay8-xg" tabindex="-1">';
echo '<span class="video-thumb ux-thumb yt-thumb-default-185 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner"><img tabindex="-1" alt="" src="/dynamic/thumbs/6HS8Tay8-xg.png" data-thumb="/dynamic/thumbs/6HS8Tay8-xg.png" width="185" loading="lazy"><span class="vertical-align"></span></span></span></span>';
echo '<span class="video-time">0:18</span>';
echo '<button class="addto-button video-actions spf-nolink addto-watch-later-button yt-uix-button yt-uix-button-default yt-uix-button-short yt-uix-tooltip" type="button" title="Watch Later" onclick=";return false;" data-video-ids="6HS8Tay8-xg" role="button" data-tooltip-text="Watch Later"><span class="yt-uix-button-content"> <img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="Watch Later">';
echo '</span></button>';
echo '</a>';
echo '</div>';
echo '<div class="feed-item-content">';
echo '<h4>';
echo '<a class="feed-video-title title yt-uix-contextlink  yt-uix-sessionlink" href="/2013/watch?v=6HS8Tay8-xg" data-sessionlink="feature=g-crec-u&amp;ei=COyI797RuLQCFSsWIQod0FCFuQ%3D%3D&amp;ved=CB8Qph4oAA%3D%3D&amp;context=G2cce68eRCGXQYbcTJ33bTQzTvVHkd_lo7_Czp9GgoOmyXwydegvU">';
echo 'test</a>';
echo '</h4>';
echo '<div class="metadata">';
echo '<span class="view-count">';
echo '8 views </span>';
echo '<div class="description">';
echo '<p></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<span class="feed-item-action-menu subscribed" data-external-id="PS1QXlm4qXKhVwi7EBoM_RGFpwdqVnAH-dqC8OhRcPzV0ngx04EJHgQ==">';
echo '<button type="button" class="flip yt-uix-button yt-uix-button-feed-item-action-menu yt-uix-button-empty" onclick=";return false;" data-button-has-sibling-menu="True" role="button" aria-pressed="false" aria-expanded="false" aria-haspopup="true" aria-activedescendant=""><span class="yt-uix-button-icon-wrapper"><img class="yt-uix-button-icon yt-uix-button-icon-feed-item-action-menu" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><span class="yt-valign-trick"></span></span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""><ul class=" yt-uix-button-menu yt-uix-button-menu-feed-item-action-menu" role="menu" aria-haspopup="true" style="display: none;"><li role="menuitem" id="aria-id-17017458839"><span data-action="hide" class="dismiss-menu-choice yt-uix-button-menu-item" onclick=";return false;">Hide this activity</span></li><li role="menuitem" id="aria-id-27652003452"><span data-subscription-id="s-g9bXtaCSKRwzCmeFkvD912YfxX4CmZ5I-IkGd8HUI" data-action="uploads" class="dismiss-menu-choice uploads yt-uix-button-menu-item" onclick=";return false;">Only show uploads from SubRocks</span></li><li role="menuitem" id="aria-id-13786163608"><span data-action="subscribe" class="dismiss-menu-choice subscribe yt-uix-button-menu-item" onclick=";return false;">Subscribe to SubRocks</span></li><li role="menuitem" id="aria-id-88805288643"><span data-channel-key="SubRocks" onclick=";return false;" data-action="unsubscribe" data-subscription-id="s-g9bXtaCSKRwzCmeFkvD912YfxX4CmZ5I-IkGd8HUI" class="dismiss-menu-choice unsubscribe yt-uix-button-menu-item">Unsubscribe from SubRocks</span></li></ul></button>';
echo '</span>';
echo '</div>';
echo '<div class="feed-item-dismissal-notices"><div class="feed-item-dismissal feed-item-dismissal-hide hid">This item has been hidden</div><div class="feed-item-dismissal feed-item-dismissal-uploads hid">In the future you will only see uploads from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-all-activity hid">In the future you will see all activity from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-unsubscribe hid">You have been unsubscribed from <span class="feed-item-owner"><a href="/2013/userr/SubRocks?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr">SubRocks</a></span>';
echo '</div></div>';
echo '</li>';
echo '</div>';
echo '<div class="feed-item-dismissal-notices"><div class="feed-item-dismissal feed-item-dismissal-hide hid">This item has been hidden</div><div class="feed-item-dismissal feed-item-dismissal-uploads hid">In the future you will only see uploads from <span class="feed-item-owner"><a href="/user/?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr"></a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-all-activity hid">In the future you will see all activity from <span class="feed-item-owner"><a href="/user/?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr"></a></span>';
echo '</div><div class="feed-item-dismissal feed-item-dismissal-unsubscribe hid">You have been unsubscribed from <span class="feed-item-owner"><a href="/user/?feature=g-u-u" class="yt-uix-sessionlink yt-user-name " data-sessionlink="feature=g-u-u" dir="ltr"></a></span>';
echo '</div></div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '<div class="feed-load-more-container scrolldetect" data-scrolldetect-callback="feed-load-more">';
echo '<button class="feed-load-more yt-uix-button yt-uix-button-hh-default" type="button" onclick=";return false;" role="button"><span class="yt-uix-button-content"> <span class="text">';
echo 'Load more';
echo '</span>';
echo '<span class="spinner">';
echo '<img src="/yts/img/pixel-vfl3z5WfW.gif" alt="Loading...">';
echo '</span>';
echo '</span></button>';
echo '</div>';
echo '</div>';
echo '<div id="feed-loading-template" class="hid">';
echo '<div class="feed-message">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="Loading icon">';
echo 'Loading...';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="feed-background"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<hr class="branded-page-v2-col-container-bottom-border">';
echo '</div>';
echo '<script id="js-2668726052" src="/yts/jsbin/www-watch7-core-vflzdEjU1.js" data-loaded="true"></script>';
echo '<script>';
echo 'function subscribe(username, pfp, userId, button) {';
echo 'var loggedIn = true;';
echo '';
echo 'if (loggedIn) {';
echo 'var isSubscribed = button.classList.contains("yt-uix-button-subscribed-unbranded");';
echo '';
echo 'if (!isSubscribed) {';
echo '// Handle Subscribe (Insert subscription record)';
echo 'var xhr = new XMLHttpRequest();';
echo 'xhr.open('POST', '/subscription_ajax?action_create_subscription_to_channel=1&feature=home&c=' + username, true);';
echo 'xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');';
echo 'xhr.onreadystatechange = function () {';
echo 'if (xhr.readyState === 4 && xhr.status === 200) {';
echo 'var data = JSON.parse(xhr.responseText);';
echo '// Update button and channel list item to reflect subscription';
echo 'button.classList.add("yt-uix-button-subscribed-unbranded");';
echo 'button.classList.remove("yt-uix-button-subscribe-unbranded");';
echo 'addGuideItem(username, userId, pfp, true);';
echo 'setTimeout(function () {';
echo '$(".guide-notification-enabled").fadeOut(500, function () {';
echo '$(this).removeClass("guide-notification guide-notification-enabled").fadeIn(0);';
echo '});';
echo '}, 1000);      // Add to the top of the guide list';
echo '} else if (xhr.readyState === 4) {';
echo 'console.error('Error:', xhr.status);';
echo '}';
echo '};';
echo 'xhr.send();';
echo '} else {';
echo '// Handle Unsubscribe (Delete subscription record)';
echo 'var xhr = new XMLHttpRequest();';
echo 'xhr.open('POST', '/subscription_ajax?action_remove_subscriptions=1&feature=home&c=' + username, true);';
echo 'xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');';
echo 'xhr.onreadystatechange = function () {';
echo 'if (xhr.readyState === 4 && xhr.status === 200) {';
echo '// Update button and remove channel list item';
echo 'button.classList.remove("yt-uix-button-subscribed-unbranded");';
echo 'button.classList.add("yt-uix-button-subscribe-unbranded");';
echo 'var guideChannels = document.getElementById('guide-channels');';
echo 'var channelItem = guideChannels.querySelector('[data-channel-id="' + userId + '"]');';
echo 'if (channelItem) {';
echo 'channelItem.parentNode.removeChild(channelItem);';
echo '}';
echo '} else if (xhr.readyState === 4) {';
echo 'console.error('Error:', xhr.status);';
echo '}';
echo '};';
echo 'xhr.send();';
echo '}';
echo '}';
echo '}';
echo '';
echo 'function addGuideItem(username, userId, pfp, addToTop) {';
echo 'var guideChannels = document.getElementById('guide-channels');';
echo 'if (guideChannels) {';
echo 'var newItem = document.createElement('li');';
echo 'newItem.className = "guide-channel guide-notification guide-notification-enabled";';
echo 'newItem.innerHTML = '<a class="guide-item guide-notification guide-notification-enabled" title="' + username + '" href="/feed/' + userId + '" data-channel-id="' + userId + '">' +';
echo ''<span class="guide-notification-icon"></span><span class="thumb"><span class="video-thumb ux-thumb yt-thumb-square-18 "><span class="yt-thumb-clip"><span class="yt-thumb-clip-inner">' +';
echo ''<img data-thumb-manual="1" alt="Thumbnail" src="/ytd/pfp/' + pfp + '" data-thumb="/ytd/pfp/' + pfp + '" width="18">' +';
echo ''<span class="vertical-align"></span></span></span></span></span>' +';
echo ''<span class="display-name">' +';
echo ''<span>' + username + '</span>' +';
echo ''</span>' +';
echo ''</a>';';
echo '';
echo 'if (addToTop) {';
echo 'guideChannels.prepend(newItem); // Add the new item to the top of the list';
echo '} else {';
echo 'guideChannels.appendChild(newItem); // Add the new item to the bottom of the list';
echo '}';
echo '}';
echo '}';
echo '';
echo '// Call the handleSubscribe function when the document is ready';
echo 'document.addEventListener('DOMContentLoaded', function () {';
echo '// Assuming the handleSubscribe() function is defined in the script.js file';
echo 'handleSubscribe();';
echo '});';
echo '';
echo '</script>';
echo '</div></div></div></div>';
echo '<div id="footer-hh-container">    <div id="footer-hh"><div id="footer-hh-main"><div id="footer-hh-logo"><a href="/" title="SubRocks home"><img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt="SubRocks home"></a></div>  <ul class="pickers yt-uix-button-group" data-button-toggle-group="optional">';
echo '<li>';
echo '';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-default" type="button" id="yt-picker-language-button" data-picker-key="language" data-picker-position="footer" data-button-action="yt.www.picker.load" data-button-toggle="true" data-button-menu-id="arrow-display" role="button"><span class="yt-uix-button-content">    <span class="yt-picker-button-label">';
echo 'Language:';
echo '</span>';
echo 'English';
echo '</span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""></button>';
echo '';
echo '';
echo '</li>';
echo '<li>';
echo '';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-default" type="button" id="yt-picker-language-button" data-picker-key="country" data-picker-position="footer" data-button-action="yt.www.picker.load" data-button-toggle="true" data-button-menu-id="arrow-display" role="button"><span class="yt-uix-button-content">    <span class="yt-picker-button-label">';
echo 'Country:';
echo '</span>';
echo 'Worldwide';
echo '</span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""></button>';
echo '';
echo '';
echo '</li>';
echo '<li>';
echo '';
echo '<button onclick=";return false;" class=" yt-uix-button yt-uix-button-hh-default" type="button" id="yt-picker-language-button" data-picker-key="safetymode" data-picker-position="footer" data-button-action="yt.www.picker.load" data-button-toggle="true" data-button-menu-id="arrow-display" role="button"><span class="yt-uix-button-content">    <span class="yt-picker-button-label">';
echo 'Safety:';
echo '</span>';
echo 'Off';
echo '</span><img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" alt=""></button>';
echo '';
echo '';
echo '</li>';
echo '</ul>';
echo '';
echo '<div id="in-product-help" class="yt-uix-clickcard">';
echo '<button onclick=";return false;" class="yt-uix-clickcard-target yt-uix-button-reverse yt-uix-button yt-uix-button-hh-default" type="button" id="help-button" data-iph-anchor-text="More Help" data-position="bottomleft" data-orientation="vertical" data-iph-search-input-text="Search SubRocks's Help Center" data-iph-title-text="Need Help on this page?" data-help-center-host="//support.google.com/youtube" data-iph-tracking="iph-questionmark" data-locale="en_US" data-iph-js-url="//s.ytimg.com/yts/jsbin/www-help-vflDI78xO.js" data-iph-topic-id="1699306" data-iph-css-url="//s.ytimg.com/yts/cssbin/www-helpie-vflVn-ywY.css" data-iph-search-button-text="Search" role="button"><span class="yt-uix-button-content">  <img class="questionmark" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '<span>Help</span>';
echo '<img class="yt-uix-button-arrow" src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '</span></button>';
echo '<div class="yt-uix-clickcard-content" id="help-target">  <p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="Loading icon">';
echo '';
echo 'Loading...';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div id="yt-picker-language-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="Loading icon">';
echo '';
echo 'Loading...';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '<div id="yt-picker-country-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="Loading icon">';
echo '';
echo 'Loading...';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '<div id="yt-picker-safetymode-footer" class="yt-picker" style="display: none">';
echo '<p class="yt-spinner">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="yt-spinner-img" alt="Loading icon">';
echo '';
echo 'Loading...';
echo '</p>';
echo '';
echo '</div>';
echo '';
echo '</div><div id="footer-hh-links"><ul id="footer-hh-links-primary">  <li><a href="/2013/t/about_subrocks">About</a></li>';
echo '<li><a href="/2013/t/press">Press &amp; Blogs</a></li>';
echo '<li><a href="/2013/t/copyright_center">Copyright</a></li>';
echo '<li><a href="/2013/creators">Creators &amp; Partners</a></li>';
echo '<li><a href="/2013/t/advertising_overview">Advertising</a></li>';
echo '<li><a href="/2013/dev">Developers</a></li>';
echo '</ul><ul id="footer-hh-links-secondary">  <li><a href="/2013/t/terms">Terms</a></li>';
echo '<li><a href="http://www.google.com/intl/en/policies/privacy/">Privacy</a></li>';
echo '<li><a href="http://support.google.com/youtube/bin/request.py?contact_type=abuse&amp;hl=en-US">Safety</a></li>';
echo '';
echo '<li><a href="http://www.google.com/tools/feedback/intl/en/error.html" onclick="return yt.www.feedback.start(yt.getConfig('FEEDBACK_LOCALE_LANGUAGE'), yt.getConfig('FEEDBACK_LOCALE_EXTRAS'), null, yt.getConfig('FEEDBACK_BUCKET_ID'));" id="reportbug">Send feedback</a></li>';
echo '<li><a href="/2013/testrocks">Try something new!</a></li>';
echo '';
echo '<li>  <span class="copyright" dir="ltr">&copy; 2023 SubRocks, LLC</span>';
echo '</li>';
echo '';
echo '</ul></div>        <div id="yt-hitchhiker-feedback">';
echo '<a class="start end" href="http://www.google.com/tools/feedback/intl/en/error.html" onclick="return yt.www.feedback.start(yt.getConfig('FEEDBACK_LOCALE_LANGUAGE'), yt.getConfig('FEEDBACK_LOCALE_EXTRAS'), null, yt.getConfig('FEEDBACK_BUCKET_ID'));">';
echo 'Send feedback';
echo '</a>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="yt-dialog hid" id="feed-privacy-lb">';
echo '<div class="yt-dialog-base">';
echo '<span class="yt-dialog-align"></span>';
echo '<div class="yt-dialog-fg">';
echo '<div class="yt-dialog-fg-content">';
echo '<div class="yt-dialog-loading">';
echo '<div class="yt-dialog-waiting-content">';
echo '<div class="yt-spinner-img"></div><div class="yt-dialog-waiting-text">Loading...</div>';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="yt-dialog-content">';
echo '<div id="feed-privacy-dialog">';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="yt-dialog-working">';
echo '<div id="yt-dialog-working-overlay">';
echo '</div>';
echo '<div id="yt-dialog-working-bubble">';
echo '<div class="yt-dialog-waiting-content">';
echo '<div class="yt-spinner-img"></div><div class="yt-dialog-waiting-text">Working...</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '<div id="shared-addto-watch-later-login" class="hid">';
echo '<div id="shared-addto-watch-later-login" class="yt-uix-button-menu yt-uix-button-menu-external " style="min-width: 20px; left: 976px; top: 1174px; display: none;"><a href="/ServiceLogin?hl=en_US&amp;uilel=3&amp;service=youtube&amp;passive=true&amp;continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26feature%3Dplaylist%26hl%3Den_US%26next%3D%252Fwatch%253Fv%253D-8GvxLPcago%26nomobiletemp%3D1" class="sign-in-link">Sign in</a> to add this to a playlist</div> </div>';
echo '<div id="shared-addto-menu" style="display: none;" class="hid sign-in">';
echo '<div class="addto-menu">';
echo '<div id="addto-list-panel" class="menu-panel active-panel">';
echo '<span class="yt-uix-button-menu-item yt-uix-tooltip sign-in" data-possible-tooltip="" data-tooltip-show-delay="750"><a href="http:https://accounts.google.com/ServiceLogin?passive=true&amp;uilel=3&amp;hl=en_US&amp;service=youtube&amp;continue=http%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26feature%3Dplaylist%26hl%3Den_US%26next%3D%252F%26nomobiletemp%3D1" class="sign-in-link">Sign in</a> to add this to a playlist';
echo '</span>';
echo '</div>';
echo '<div id="addto-list-saved-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<div class="yt-alert yt-alert-naked yt-alert-success  "> <div class="yt-alert-icon">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="icon master-sprite" alt="Alert icon">';
echo '</div>';
echo '<div class="yt-alert-content" role="alert"> <span class="yt-alert-vertical-trick"></span>';
echo '<div class="yt-alert-message">';
echo '<span class="message">Added to <span class="addto-title yt-uix-tooltip yt-uix-tooltip-reverse" title="More information about this playlist" data-tooltip-show-delay="750"></span></span>';
echo '</div>';
echo '</div></div>';
echo '</div>';
echo '</div>';
echo '<div id="addto-list-error-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '<span class="error-details"></span>';
echo '<a class="show-menu-link">Back to list</a>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-input-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<div class="yt-alert yt-alert-naked yt-alert-success  "> <div class="yt-alert-icon">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="icon master-sprite" alt="Alert icon">';
echo '</div>';
echo '<div class="yt-alert-content" role="alert"> <span class="yt-alert-vertical-trick"></span>';
echo '<div class="yt-alert-message">';
echo '<span class="message">Added to playlist:</span>';
echo '<span class="addto-title yt-uix-tooltip" title="More information about this playlist" data-tooltip-show-delay="750"></span>';
echo '</div>';
echo '</div></div>';
echo '</div>';
echo '<div class="yt-uix-char-counter" data-char-limit="150"><div class="addto-note-box addto-text-box"><textarea id="addto-note" class="addto-note yt-uix-char-counter-input" maxlength="150"></textarea><label for="addto-note" class="addto-note-label">Add an optional note</label></div><span class="yt-uix-char-counter-remaining">150</span></div> <button onclick=";return false;" disabled="disabled" class="playlist-save-note yt-uix-button yt-uix-button-hh-default" type="button" role="button"><span class="yt-uix-button-content">Add note </span></button>';
echo '</div>';
echo '<div id="addto-note-saving-panel" class="menu-panel">';
echo '<div class="panel-content loading-content">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '<span>Saving note...</span>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-saved-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '<span class="message">Note added to:</span>';
echo '</div>';
echo '</div>';
echo '<div id="addto-note-error-panel" class="menu-panel">';
echo '<div class="panel-content">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif">';
echo '<span class="message">Error adding note:</span>';
echo '<ul class="error-details"></ul>';
echo '<a class="add-note-link">Click to add a new note</a>';
echo '</div>';
echo '</div>';
echo '<div class="close-note hid">';
echo '<img src="//s.ytimg.com/yts/img/pixel-vfl3z5WfW.gif" class="close-button">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<script>';
echo 'if (window.yt.timing) {yt.timing.tick("js_head");}    </script>';
echo '<script id="www-core-js" src="/yt/jsbin/www-core-vfl1pq97W.js" data-loaded="true"></script>';
echo '<script id="www-core-js" src="/yt/jsbin/www-core-vfl1pq97W.js" data-loaded="true"></script>';
echo '<script>';
echo 'var searchBox = document.getElementById('masthead-search-term');';
echo 'if (searchBox) {';
echo 'searchBox.focus();';
echo '}';
echo 'yt.setConfig('FEED_DEBUG', true);';
echo 'yt.setConfig('GUIDE_VERSION', 2);';
echo '';
echo '</script>';
echo '<script>';
echo 'window.masthead = new yt.www.ads.MastheadAd(';
echo '"ThoiN024RrM",';
echo 'true);';
echo '';
echo 'yt.www.guide.init();';
echo '';
echo '';
echo '';
echo '</script>';
echo '<script id="js-1061990701" src="/yts/jsbin/www-guidev2-vfl72MaxY.js" data-loaded="true"></script>';
echo '<script>';
echo 'yt.setConfig({';
echo ''GUIDE_SELECTED_FEED': "highlights"         });';
echo '</script>';
echo '<script>yt.setConfig({'EVENT_ID': "CPHWmt_vxbQCFS4VIQodzlgcTg==",'LOGGED_IN': true,'SESSION_INDEX': null,'CURRENT_URL': "https:\/\/rblx2023.serv00.net\/",'WATCH_CONTEXT_CLIENTSIDE': true,'FEEDBACK_BUCKET_ID': "Home",'FEEDBACK_LOCALE_LANGUAGE': "en",'FEEDBACK_LOCALE_EXTRAS': {"accept_language": null, "logged_in": false, "guide_subs": 8, "experiments": "904000,906373,923014,902553,916613,916708,920704,912806,928001,922403,922405,929901,913605,929104,913546,913556,908496,920201,913302,919009,900816,911116,902554,901451,902556"}});yt.setMsg({'ADDTO_WATCH_LATER_ADDED': "Added",'ADDTO_WATCH_LATER_ERROR': "Error"});yt.setAjaxToken('addto_ajax_logged_out', "0YcMRWgAlQphWmsmtL83sNyVZrZ8MTM1NzA4NTU0M0AxMzU2OTk5MTQz");  yt.setConfig('FEED_PRIVACY_CSS_URL', "\/yts\/cssbin\/www-feedprivacydialog-vfl_3sjoJ.css");';
echo 'yt.setAjaxToken('feed_privacy_ajax', "");';
echo 'yt.pubsub.subscribe('init', yt.www.account.FeedPrivacyDialog.init);';
echo 'yt.setConfig({'SBOX_JS_URL': "\/yts\/jsbin\/www-searchbox-vflMOcX4x.js",'SBOX_SETTINGS': {"HAS_ON_SCREEN_KEYBOARD": false, "CLOSE_ICON_URL": "\/yts\/img\/icons\/close-vflrEJzIW.png", "EXPERIMENT_ID": -1, "REQUEST_DOMAIN": "us", "PSUGGEST_TOKEN": null, "IS_HH": true, "REQUEST_LANGUAGE": "en", "SESSION_INDEX": null, "SHOW_CHIP": false, "CHIP_PARAMETERS": {}},'SBOX_LABELS': {"SUGGESTION_DISMISS_LABEL": "Dismiss", "SUGGESTION_DISMISSED_LABEL": "Suggestion dismissed"}});</script> <script>';
echo 'if (window.yt.timing) {yt.timing.tick("js_page");}    </script>';
echo '<script>';
echo 'yt.setConfig('TIMING_ACTION', "glo");    </script>';
echo '<script>yt.setConfig({'XSRF_TOKEN': "gt1OcUzX0E0XLlUpO_wwn2bX4DB8MTM1NzA4NTU0M0AxMzU2OTk5MTQz",'XSRF_REDIRECT_TOKEN': "0ubE01xULmCFMs5UZ5Lh1AptiBt8MTM1NzA4NTU0M0AxMzU2OTk5MTQz",'XSRF_FIELD_NAME': "session_token"});</script><script>yt.setConfig('THUMB_DELAY_LOAD_BUFFER', 300);</script> <script>';
echo 'if (window.yt.timing) {yt.timing.tick("js_foot");}    </script>';
echo '<div id="debug"></div>';
echo '<iframe class="gstl_0 gssb_k" style="display: none;" allow="autoplay 'self'; fullscreen 'self'"></iframe><table style="width: 489px; display: none; top: 103px; left: 225px; position: absolute;" class="gstl_0 gssb_c" cellspacing="0" cellpadding="0"><tbody><tr><td class="gssb_f"></td><td class="gssb_e" style="width: 100%;"></td></tr></tbody></table></body></html>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
?>